### ISSUE TITLE
Wording change/agreement throughout: Global tables to show "employees" and "non-employees"

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#101]
Wording change/agreement throughout: Global tables to show "employees" and "non-employees"

**Comment by nukeador** [comment]
To be asigned to @alpgarcia

**Comment by alpgarcia** [comment]
Community metrics updated applying this: https://github.com/Bitergia/mozilla-contribution-analysis/blob/master/data-analysis/rc1/html/Community.html
