### ISSUE TITLE
Implement employees identification based on provided list with dates

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#102]

**Comment by nukeador** [comment]
To be asigned to @alpgarcia

**Comment by nukeador** [comment]
please, make sure this list is only used offline and it's NOT uploaded anywhere else or to the dashboard.

**Comment by sanacl** [comment]
I have a question. What if we have people marked as Mozilla Staff that are not included in that list? Should we consider that in order to be a Mozilla Staff members people have to be included in this list?

**Comment by nukeador** [comment]
Can we do a quick check to see what are the differences?

**Comment by jgbarah** [comment]
We need to move this forward. We have decided to use the following algorithm, according to past talks:

* If the person is only in Staff, use dates as staff for considering "Staff", and "Community" for the rest of their activity (if any).
* If the person is only in Reps, use the dates as rep for considering "Rep", and "Community" for the rest of their activity (if any).
* If the person is both in Staff and Reps, use the dates as staff for being considered in "Staff", and the dates being rep but not staff as "Rep". Community for the rest of their activity (if any).

Then, we will consider Staff & Code Sheriff as employees, and Reps and Community as non-employees (please not that therefor, reps are considered non-employees while they are not staff, but employees while they are staff).

**Comment by nukeador** [comment]
This is great, thanks for the update Jesus.

Please note that with the recent changes we have splitted reps into "Mozilla Reps" and "Funcional Reps".

Cheers.

**Comment by sanacl** [comment]
83 out of 2857 entries in the Mozilla Staff file have a starting date > end date. I'm discarding these 83 contributors unless you guys update me about what to do with their dates.

Idea: date fields could be swapped for these 83 guys

**Comment by nukeador** [comment]
Yes, thanks Luis. I'm asking HR about these and if it's safe to assume it's a typo and we can switch dates.

**Comment by jgbarah** [comment]
@nukeador please see comments about "Functional Reps" in #98.

**Comment by nukeador** [comment]
@sanacl this is the reply from HR

"Yes, so in the cases where there are term dates that are displayed, but the hire date is later than the term date, means that the employee has been rehired back into Mozilla, or converted from contractor into employee.  The termination date stays, but it was a part of the former hire date.  Hope that helps."

**This means:** Employees with start date later than end date are STILL employees today and we should ignore the end that (and probably put 2099)

**Comment by alpgarcia** [comment]
We have found a bug in the update process that requires a complete re-run of the affiliation script. We expect to have data ready for git by tomorrow.

In the meanwhile we are going to prepare some panels in our reports' environment, similar to the ones you have in your production environment. The idea is to allow you to check affiliations once data is ready in the indexes. Once we get the panels ready, I'll send you some instructions to access them using credentials we sent you.

**Comment by alpgarcia** [comment]
As promised, I uploaded some panels to Kibana in `mozilla-test` environment. Once data is ready, please use them for data validation. To load panels:
* Go to https://mozilla-test.biterg.io/edit  (use same credentials provided to run notebooks)
* In the left hand side menu, chose `Dashboard`
* Click on `Open` in the top right corner menu. A list of available panels will appear.
* Chose the panel you are interested in and start checking data :)

**Comment by sanacl** [comment]
Affiliation data is already applied to Git and Bugzilla indexes.
Some restrictions:
* the 83 guys (2% of the Mozilla Staff people) with a start_date > end_date were not modified, so they are in the "Mozilla Staff" bucket with the maximum period (from 1900 to 2100)
* only two intervals of affiliation are supported. If Alice was Rep, then Staff and became Rep again. We'll only see Rep and Staff. The third interval won't be associated to Rep, so in the report it will appear as 'Unknown'.

**Comment by nukeador** [comment]
Can we use "Non-employee" or "Community" instead of creating a new group called "Unknown"?

Thanks

**Comment by alpgarcia** [comment]
@nukeador said:
> Can we use "Non-employee" or "Community" instead of creating a new group called "Unknown"?

Currently is not supported in the ad-hoc script @sanacl used to update affiliations. We will take care to substitute it in the report to avoid more delays in data enrichment.

Today we'll start updating report data with refreshed indexes information.

**Comment by nukeador** [comment]
OK, let's make sure this is applied to all indexes so we can fetch the right data from reports.

**Comment by sanacl** [comment]
Information already applied to all the indexes. I think we can close this ticket.
