### ISSUE TITLE
Gather a list of survey groups and fields we are interested in cross-reference

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#103]
Gather a list of survey groups and fields we are interested in cross-reference

**Comment by nukeador** [comment]
This should include fields from data analysis we consider most relevant.

**Comment by nukeador** [comment]
Here you have the list, let me know if it's useful

## Activity

* **Column I:** Have you contributed to a Mozilla or related project within the past year? 

Options we'll track (yes, active. no, inactive)
* Yes, I have contributed within the past year.
* No, I have not contributed within the past year, but I have contributed to a Mozilla or related project in the past.

## Contribution areas (projects)
* **From Column O to Column AP**: These are the contribution areas for inactive people
* **From JF to KG**: Active contributors, contribution areas in the past year.
* **LB**: Active people who report coding as an activity.

## Motivation

* **From Column CJ to Column DO**: Reasons inactive people to stop their contributions
* **DY to FI**: Inactive contributors, motivations to contribute.
* **From NQ to OI**: Active contributors, barriers to contribute
* **From PE to QQ**: Active contributors, motivations to contribute.

## Demographics

* **From QX to RB**: Employment/educational status
* **From RG to RI**: Open source orgs they contribute
* **RN**: Age
* **RO**: Country
* **RP**: Gender
* **From RS to RZ**: Sexual orientation
* **SD**: Disability
* **DF**: Education level
* **SG to SH**: Main language
* **SI**: English proficiency
* **SJ**: Github
* **SK**: Email
* **SL**: Bugzilla

**Comment by alpgarcia** [comment]
Thanks! We will start trying to use those fields with a restricted number of possible answers.
