### ISSUE TITLE
First draft of the cross-referencing analysis

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#104]
Expectations:

* Data from the survey is incorporated (#97)
* Updated data from gecko-dev to exclude Firefox-only code (#110 #100)
* Improved data for employee count (#102)
* Improved data for Mozilla Reps (#98)
* All comments from the May 29th version applied.
    * Show all data per project
    * Show all data for non-employees
    * Minor changes to charts, updates...

**Comment by nukeador** [comment]
Depends on #103

**Comment by alpgarcia** [comment]
Are people answering the survey non-employees only?

**Comment by nukeador** [comment]
Yes, only non-employees

**Comment by alpgarcia** [comment]
From the May 29th version of the report we expect to fix:
- As much as possible, show data per project
- As much as possible, show data for non-employees
- Include Code Sheriff, Reps, Mozilla Stuff, Community.
- Minor changes to charts, updates, etc

**Comment by alpgarcia** [comment]
> Yes, only non-employees

Then there is something weird somewhere. I found a user with a lot of activity in Git and Mailing lists. I looked for the corresponding UUID in our indexes and I found he is marked as Mozilla Staff. His GitHub username is 'gerv'.

I looked for another one with high activity and I found 'djmitche', that is a similar case, also Mozilla Staff.

This is very important because it seems we can't assume identities from survey as non-employees and, in that case, we need to filter survey identities to focus on non-employees.

**Comment by nukeador** [comment]
So yes, I see now some known employees replied the survey and didn't identified themselves as such. We should filter them out using our lists.

**Comment by alpgarcia** [comment]
Ok, I'll add a filter to retrieve only those associated to Mozilla Staff and Code Sheriffs from our indexes.

Is that correct?

**Comment by alpgarcia** [comment]
Data per project refreshed for community metrics (i.e. number of authors). This also affects to: #100 and #101. 

Still needs to be included in the report, though data is already available at:
https://github.com/Bitergia/mozilla-contribution-analysis/blob/master/data-analysis/rc1/html/Community.html

**Comment by nukeador** [comment]
> Ok, I'll add a filter to retrieve only those associated to Mozilla Staff and Code Sheriffs from our indexes.

Yes, filter these out.

**Comment by jgbarah** [comment]
From the title of this issue:

> First draft of the cross-referencing analysis

This is for the cross-referencing analysis (I understand that cross-referencing with the survery data) or for all the report?

**Comment by nukeador** [comment]
This is for incorporating the survey data with the existing report, as well as any other pending improvements (listed in the description).

At the end of this week we will get feedback from the report that will be able to incorporate in the next iteration (#105) on June 15th together with the data from the github project.

**Comment by alpgarcia** [comment]
I've created #111 to track survey data analysis progress.

**Comment by alpgarcia** [comment]
@nukeador which version of the google doc should we update?

I am working on the original version to keep the comments we had (not the copy made by George). Is this correct?

**Comment by nukeador** [comment]
Yes, that's correct.

**Comment by geroter** [comment]
Maybe let's give them back a copy of the clean version that had some
changes I made instead?

**Comment by nukeador** [comment]
@alpgarcia @jgbarah Please, check George's copy history for changes done pre-workshop, so we make sure these are incorporated in the current work in progress doc

https://docs.google.com/document/d/1sdPM0UXjs7T0i7ZtSD31YAbeiPRykualn6ytG11R97M/edit

**Comment by alpgarcia** [comment]
Ok, we'll have a look at the changes to update the copy we are working on.

**Comment by dicortazar** [comment]
I'm starting to produce the insights in the main document for this cross-referenced analysis.

**Comment by alpgarcia** [comment]
@nukeador, it seems there is a limitation with discourse. As messages can have several categories, there is no clear way of deciding to which project it belongs to.

**Comment by alpgarcia** [comment]
@alpgarcia said:
> @nukeador, it seems there is a limitation with discourse. As messages can have several categories, there is no clear way of deciding to which project it belongs to.

I said nothing. It was a misunderstood in our side. It seems we can do it using category_id. Sorry for introducing noise.

**Comment by nukeador** [comment]
Let's continue in https://github.com/mozilla/participation-metrics-org/issues/105 since it's about the delivery for this week.
