### ISSUE TITLE
First iteration of the final report including cross reference data and Github external analysis delivered

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#105]
### Pending improvements

* General
  - [X] Update the six projects charts, and add some for non-employees
  - [X] Update the text about the ratio between no-employees and employees
  - [X] Check Servo - Gecko relation to understand the difference between the first contributors in a project and the first contributors in Gecko, being Gecko the first where they commit.
  - [X] Integrate George comments from first final version into the working-version (In progress till page 30)

* Survey cross-reference
  - [X] Add TZ chart to add context to the countries information
  - [X] Add a disclaimer about the population of the survey and how the boxplots might be skewed by small populations
  - [X] Firefox and women participating in the bug reporting (not added)
  - [X] Add a table in the coverage section
  - [ ] Have a look at the draft for the survey results and check if we can have something else from the quantitative point of view

* GitHub external contributions section
  - [X] use the threshold project_commits:>5 as we're removing noise from the analysis
  - [X] Ignore Mozilla Foundation and mozilla-b2g organizations in GitHub
  - [X] In too general organizations, drill down a bit into the data (not general orgs after the threshold)

**Comment by dicortazar** [comment]
Work to be done after today's meeting
* Survey analysis:
  * Add TZ chart to add context to the countries information
  * Add a disclaimer about the population of the survey and how the boxplots might be skewed by small populations
  * Firefox and women participating in the bug reporting
  * Add a table in the coverage section
  * Have a look at the draft for the survey results and check if we can have something else from the quantitative point of view
* GitHub external contributions section:
  * use the threshold project_commits:>5 as we're removing noise from the analysis
  * Ignore Mozilla Foundation and mozilla-b2g organizations in GitHub
  * In too general organizations, drill down a bit into the data
  * Integrate George comments into our doc
* General doc:
  * Update the six projects charts, and add some for non-employees
  * Update the text about the ratio between no-employees and employees
  * Check Servo - Gecko relation to understand the difference between the first contributors in a project and the first contributors in Gecko, being Gecko the first where they commit.
  * Integrate George comments from first final version into the working-version

**Comment by nukeador** [comment]
Thanks @dicortazar updating the issues description

**Comment by dicortazar** [comment]
Regarding to this comment: 
> Check Servo - Gecko relation to understand the difference between the first contributors in a project and the first contributors in Gecko, being Gecko the first where they commit.

Even if there's a bias in the commits given that Gecko and Servo are together at some point, the big differences between plots for Gecko suggest that this is not due to the aggregation of Servo and Gecko.
When Servo has a difference of 100, Gecko has a difference of 300 (newcomers to the projects already contributing to Mozilla).

We're marking this task as done cause of this reason.

**Comment by dicortazar** [comment]
"Have a look at the draft for the survey results and check if we can have something else from the quantitative point of view"
There are a couple of topics we can add to the current doc from the survey doc. I see that the survey already has some feedback from the quantitative doc.
@nukeador from my side, reading both documents may raise some conclusions, but not sure if we should include those in the current report. Eg: claimed activity in the several data sources VS actual activity seen from a quantitative perspective. This is a bit out of topic from both docs, but that's perhaps a valuable conclusion at some point.
