### ISSUE TITLE
Provide every identity from survey results

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#107]
So Bitergia can check where do we have data about these identities.

**Comment by alpgarcia** [comment]
@nukeador can I expect to have response ids correctly associated to the tuple [github handle, email, bugzilla email] in the fake data?

**Comment by nukeador** [comment]
Yes, that tuple was not randomized. I'll be providing a more complete full list later today.

**Comment by nukeador** [comment]
@alpgarcia we have 589 identities for the cross-reference. Check the shared document to check how much information we have about these.

**Comment by alpgarcia** [comment]
It would be possible to have response id column in this document?

I don't need it to find them, however it would be very useful when merging survey data on your side.

**Comment by nukeador** [comment]
What do you mean by "reponse id column" if that's the column from the survey results, obviously that would identify people with responses and we can't provide that.

**Comment by alpgarcia** [comment]
I understood response id was not randomized in the fake data. In fact, I won't have access to responses so response ids are as valid as emails to identify people.

Would you have 5 mins to quickly talk about this today?

Thanks!

**Comment by nukeador** [comment]
Reponse id was not, but the rest of identificable columns were, so reponse ids and answers can't be linked to a person.

If I understand correctly you want all response ids, which I can provide, but not linked to an email or any other identificable answer, because that would allow to match reponses from the fake data with the person.

**Comment by alpgarcia** [comment]
Ok, understood. I thought response ID was also kept in the tuple and not associated with responses.
