### ISSUE TITLE
Survey Metrics Definition

### ISSUE THREAD

**Issue by alpgarcia** [mozilla/participation-metrics-org#111]
Survey analysis will be focused on the combination of the two following lists:

List of fields to analyze from Survey:
* age
* country
* gender
* disability
* education level
* language
* english proficiency

List of fields to compare with:
* commits
* pull requests
* issues
* bugs
* emails
* messages
* number of git projects
* number of github projects
* number of bugzilla projects
* number of mbox projects
* number of discourse projects

As a result we will obtain a number of plots that should allow to vizualize the distribution of the second list values versus survey answers. This analysis will be 1 to 1, e.g. age-commits, age-bugs, etc.

**Comment by alpgarcia** [comment]
Two notebooks have been created:
- [Survey Check](https://github.com/Bitergia/mozilla-contribution-analysis/blob/master/data-analysis/rc1/Survey%20Data%20Check%20.ipynb)
- [Survey Analysis](https://github.com/Bitergia/mozilla-contribution-analysis/blob/master/data-analysis/rc1/Survey%20Analysis.ipynb)

First one should be executed by @nukeador. Please check if output makes sense for Mozilla. Results must not be returned to Bitergia. If need help to understand something, please ask me.

Second one should be executed also by @nukeador. Once results are ready, please double check it doesn't contain sensitive information. You should see just numbers and plots. If everything is correct, export notebook as HTML and return it to Bitergia. As HTML does not contain any additional data than those visualized, Bitergia won't receive any information of individuals, just numbers and plots.

**Comment by nukeador** [comment]
@alpgarcia where should I place the real uuids and survey result files? Replace the sample ones under /data with the same name?

**Comment by alpgarcia** [comment]
@nukeador at the beginning of the notebooks you should see the following code:
```
############# MODIFY YOUR SURVEY CSV FILE HERE ######################################
survey_df = ut.load_survey_df(survey_filepath='../data/survey-fake.csv',
uuids_filepath='../data/uuids.csv')
#####################################################################################
```
You can put your files there in data folder, and then just modify the notebooks accordingly. For the uuids you can name it as `uuids.csv` and you won't need to modify anything. For the survey, you could do the same, but maybe naming the file `survey-fake.csv` could be a little misleading for you :)

**Comment by nukeador** [comment]
Survey Analysis html report sent back to @alpgarcia

**Comment by jgbarah** [comment]
We've been considering how better to do this. The main problem is with the structure of the spreadsheet, which has tons of columns, with little structure. For example, some questions have several columns with mutiple-option answers, while other not. We´ ŕe figuring out how to produce data structures and visualizations that help to find interesting information, but time is short.

We were thinking about producing pies and bar charts per project per answer, but that would mean *a lot* of charts, quite difficult to overview. Now, we're more in favor of using boxplots for columns that allow that (showing activity per answer, for example), and tables per project and if possible multi-project, to detect differences between projects.

@alpgarcia will comment further and produce a new version of the notebook.

But we need to clearly define an scope, or we're going to be lost in data.

**Comment by alpgarcia** [comment]
@nukeador is there any possiblity to have motivations grouped in the same column (or 3 columns, one per answer)?

To try to focus efforts an clarify what we are working on, I'll write a list. For each of the top 6 projects:
* **Coverage**: people answering the survey and contributing to the given project versus people active in the project. This is related to significance of results.
* **Demography**: diversity versus activity. For example, number of commits by gender, number of pull requests by country, etc. These are the boxplots @jgbarah commented above.
* **Motivation**: try to find their distribution within each project. It will help us a lot if you could do something similar to what I've asked you for above.

Please note we will generate a number of plots to analyze and find stories or support insights we found previously.

To give another example on demography, from survey we could draw a plot like the attached one to reinforce gender diversity analysis. If these data were confirmed after running the survey with real data, it seems that number of women is 17 vs 242 men and also their contributions are smaller in terms of pull requests. However if we look at bugs (second screenshots) we would find a very different situation, which seems to be a potential highlight we did not notice before.


![captura de pantalla de 2017-06-08 20-34-06](https://user-images.githubusercontent.com/3502941/26944781-ffa3d450-4c89-11e7-9f04-9ae147eabb74.png)

![captura de pantalla de 2017-06-08 20-39-05](https://user-images.githubusercontent.com/3502941/26944963-8f0b9812-4c8a-11e7-8ee5-ae3e4e8d0ede.png)

**Comment by nukeador** [comment]
> @nukeador is there any possiblity to have motivations grouped in the same column (or 3 columns, one per answer)?

I don't know the answer, the exported spreadsheet is the only thing I got and I assume it's the only way surveygizmo exports the data. Is there something we can do to the data to be easier for you to parse?

**Comment by alpgarcia** [comment]
If, at least for motivations, you could group results to have only one column for each question, it would help a lot. For instance, having just one column named 'Motivation leaving' with values separated by semicolons or any other char not used in possible answers.

Does it makes sense to you?

**Comment by nukeador** [comment]
It makes sense, but I would need something to make that change automatically. Can you provide us intructions/tool/code?

**Comment by alpgarcia** [comment]
Nope :(,  if I had a way to do it automatically it would be already done :)

**Comment by nukeador** [comment]
Then I guess we'll have to stick with the current format.

**Comment by jgbarah** [comment]
@nukeador said:
> The main purpuse of cross-referecing data from the survey is to incorporate data we don't have from our sources, the most important ones:
>
>    Motivations (for joining and leaving)
>    Open Source networks
>    Demography.
>
> All of this visualized by project, specially for our top 6

Something that we don't understand is that it seems that you already have data in the survey about the Mozilla project(s) in which they have contributed. If that's the case, you can already do a complete analysis per project just by using the data from the survey, which would be far more accurate than anything we may do (since we don't have a complete coverage of identified developers). Am i missing something?

In any case, this assumption by us that the per project analysis could be done just with the results of the survey, not needing to cross data with the dashboard, was what lead us to the focus that @alpgarcia proposed at the beginning of this ticket: correlations between metrics found in the survey and others found in the dashboard, but not available in the survey (such as level of activity in data sources, or experience in the project).

We're trying to provide what you are asking now, but my gut feeling is that those data are much less interesting and reliable.

**Comment by jgbarah** [comment]
@nukeador said:
> Then I guess we'll have to stick with the current format.

OK. But in that case, we're going to need significant effort (given the deadlines we have) just to extract that info from the spreadsheet in an useful format.

**Comment by jgbarah** [comment]
@nukeador said:
> Open Source networks

For this, we have found two columns, RH & RI, with current and past contributions to projects. The problem with them is that they seem to be text-free, usually separated by commas (but not always, for example "Alaveteli and varisous civic having projects"). We are going to try to use some heuristics for extracting relevant information (names of projects), but again that's going to be some effort, and I'm not sure if we're not going to lose some accuracy in the process. Just for you to know ;-)

**Comment by alpgarcia** [comment]
@nukeador said:
> Demography.

Here we will provide a comparison between activity of each different group extracted from survey. Groups come from survey answers and were specified above in task description. I gave some examples of what you can expect in [my previous comment](https://github.com/mozilla/participation-metrics-org/issues/111#issuecomment-307191827).


@nukeador said:
> Motivations (for joining and leaving)

Reading data is not trivial. What we could do is dealing with each response as if it was a binary answer (e.g. is improving your skills a motivation to join?). Then we will have a column for each possible answer and compute percentage of each of them (x% joined Mozilla to improve their skills, y% joined ...). So we will end with a table where for each motivation you'll find number or percentage of people.  A step further could be adding activity info to this table, e.g., median of contributions in git of people who joined for a given reason. Doing this will be difficult, so we work on this once the rest of things are ready.

All of this will be done for each of the top 6 projects. 

About **Coverage** I mentioned above, I expect to provide you an update of the notebook to be executed asap and check results, both global data and data by top 6 project, always for Non-Employees.

Please tell us if you have a different idea or suggestion on how to deal with these data.

**Comment by nukeador** [comment]
@jgbarah We have to differenciate the contribution area people self-reported vs the actual data we have on what these people have been contributing to. This is related with what's I comment on visualizing what we have from the people replying the survey on our data sources.

Obviously the value is to enrich our exiting data with the survey data to improve the insights, even if we can't say it's a fully representation of the population in some cases.

The way I see it, if we got, let's say, 100 people on the survey who are contributing to Rust and we have data from them on the sources, even if the total population last year for rust was 1000 non-employees, we still can enrich the data saying about motivations, demograpics, network and such.

**Comment by alpgarcia** [comment]
@nukeador could you please update your copy of the repo, execute 'Survey Anlaysis' notebook and send us back results in HTML format?

There are more things to come but we would like to have a glance to some coverage results and some plots we find interesting related to newcomers and diversity.

**Comment by nukeador** [comment]
Updated report sent.

**Comment by jgbarah** [comment]
> Obviously the value is to enrich our exiting data with the survey data to improve the insights, even if we can't say it's a fully representation of the population in some cases.

> The way I see it, if we got, let's say, 100 people on the survey who are contributing to Rust and we have data from them on the sources, even if the total population last year for rust was 1000 non-employees, we still can enrich the data saying about motivations, demograpics, network and such.

I guess I understand what you mean. And in particular, the difference between what people self-repoprt and what is found in the repositories is important. But I just wanted to highlight that, assuming people self-report correctly on where they contribute, the data about motivation, etc. can be obtained and analyzed just with the data in the survey. This said, we're already producing the information with data from the dashboard, so no problem from our side.

**Comment by alpgarcia** [comment]
@nukeador notebooks to analyze survey by project were added to the repo. Could you execute them? (please execute also the general one to ensure we use same data for all of them)

Thanks!

**Comment by nukeador** [comment]
As we talked yesterday, we are closing this and continue tracking on #112 and #104
