### ISSUE TITLE
Tools for doing queries to specific set of identities

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#115]
We would need a way/tool to be able to generate queries for a set of identities ad-hoc, without having to create a new organization for them.

And example would be a set of emails from the survey we are interested in because they represent a motivation type and country, but we don't need a permanent organization for them.

**Comment by alpgarcia** [comment]
A quick and flexible solution could be:
1. Identify people in the group you are interested in.
2. Get their uuids from CSV file I shared with you to run survey notebooks. To do it quickly you just need to merge your survey results with our uuids using same fields we matched.
3. Create a filter in the dashboard with the list of uuids.

The JSON for such a filter should be something like:
```
{
  "query": {
    "terms": {
      "author_uuid": [
        "3423fd49eda01df258d45abc1bc327a3a21fcf48",
        "495de28ead35093395abfbe10fec15856ddedf8c",
        "732ea8423f04ff6f8857d24d4184fec1d75465d2"
      ]
    }
  }
}
```
As you can see you just need to paste the uuid list. I've created a filter for you to test:
https://mozilla-test.biterg.io/edit/goto/0034a638d901a8dff5c32e15449bec03

You can rename filter as you wish or add more uuids. To share results, use `Share` link in the top right corner. If you want to save the panel to make sure your filter will not be lost, use the `Save` link in the top right corner and give the panel a new name to keep the original as it is. For panel naming, you can follow [our naming conventions for customers](https://github.com/grimoirelab/panels/blob/master/doc/dashboard-customization.md#naming-conventions).

We can schedule a quick 15 min. conf to show you the whole process.

**Comment by nukeador** [comment]
How can we generate uuids from emails? The issues is that most probably we need to do this with identitities that are not on that survey list.

**Comment by alpgarcia** [comment]
We could prepare a python script to do that but you'd need access to SortingHat. I need to ask @sanacl if it would be possible.

**Comment by alpgarcia** [comment]
It seems we could make a copy of SortingHat database to give you access. We could write a python script able to read a CSV with a list of emails, returning another CSV with each of them associated to its uuid.

Does it sound reasonable @nukeador ?

BTW, how many entities would you need to filter at same time? (we need to check maximum number of query terms supported by elastic search)

**Comment by nukeador** [comment]
That would be helful yes.

I can't estimate a number since this is going to depend from case to case, from 10 to 300? ;-)

**Comment by nukeador** [comment]
Hi, any updates here? :-)

Thanks!

**Comment by alpgarcia** [comment]
I hope the script will be ready in a couple of hours.

We would need to know where we could make a copy of  your SortingHat database. It should be somewhere you can access directly or through an SSH tunnel, but not your production machine to avoid problems. It could even be your own machine, you just need MySQL installed and the database dump (you choose where and how we can share it). In this case, we will provide you the command to load data into your database.

**Comment by alpgarcia** [comment]
Script added to GitHub repo:
https://github.com/Bitergia/mozilla-contribution-analysis/blob/master/data-analysis/tools/get_uuids_from_emails.py

I've added some documentation in:
https://github.com/Bitergia/mozilla-contribution-analysis/blob/master/data-analysis/tools/README.md#get_uuids_from_emailspy

**Comment by nukeador** [comment]
@alpgarcia Is this a DB we can have directly on our servers instead of doing a copy? (I just want to understand this for the long term usage of this)

@hmitsch In that case, can we have this hosted in our infra? (I would prefer so it's not just me the only one able to do queries)

**Comment by alpgarcia** [comment]
At this point, @sanacl is the person you need. SortingHat database is currently in your production servers (well, right now is not the version we have for the report, but it should be updated at some point). Working against a copy ensures not to break anything in the worst case.

Anyway, I think you could talk directly to @sanacl as he is who manages this stuff.

**Comment by nukeador** [comment]
I've pinged @sanacl by email

**Comment by sanacl** [comment]
@nukeador The DB is already in your servers. I guess you would need just read access, is that right?

**Comment by nukeador** [comment]
I expect more of these request coming in the future, and yes, read only access is fine.

Cheers.

**Comment by hmitsch** [comment]
I'd really like to have a broader conversation around this topic. Please do no close this ticket before prior consultation with me. I expect we discuss this ticket at one of the future Bitergia-Mozilla calls.

Best regards,
   Henrik

**Comment by nukeador** [comment]
@alpgarcia I have access to the server but I can't run the script because I miss all dependencies. Can you generate a requirements.txt I can use?

Thanks!

**Comment by nukeador** [comment]
I managed yo figure out requirements, also there is a change needed on the script to make it work, @alpgarcia please check https://github.com/Bitergia/mozilla-contribution-analysis/pull/3

**Comment by nukeador** [comment]
So apparently this is working. We should figure out a way where ther eis no need for a person with ssh access + technical knowledge to generate the uuids and query

**Comment by nukeador** [comment]
For reference [this would be the link](https://analytics.mozilla.community//edit/app/kibana#/dashboard/Git?_g=(filters:!(),refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(filters:!((%27$state%27:(store:appState),meta:(alias:%27Empty%20Commits%27,disabled:!f,index:git,key:files,negate:!t,value:%270%27),query:(match:(files:(query:%270%27,type:phrase)))),(%27$state%27:(store:appState),meta:(alias:Bots,disabled:!f,index:git,key:author_bot,negate:!t,value:%271%27),query:(match:(author_bot:(query:1,type:phrase)))),(%27$state%27:(store:appState),meta:(alias:uuids,disabled:!f,index:git,key:query,negate:!f,value:%27%7B%22terms%22:%7B%22author_uuid%22:%5B%223423fd49eda01df258d45abc1bc327a3a21fcf48%22,%22495de28ead35093395abfbe10fec15856ddedf8c%22,%22732ea8423f04ff6f8857d24d4184fec1d75465d2%22%5D%7D%7D%27),query:(terms:(author_uuid:!(%273423fd49eda01df258d45abc1bc327a3a21fcf48%27,%27495de28ead35093395abfbe10fec15856ddedf8c%27,%27732ea8423f04ff6f8857d24d4184fec1d75465d2%27))))),options:(darkTheme:!f),panels:!((col:7,id:git_commits_organizations,panelIndex:1,row:1,size_x:3,size_y:4,title:Organizations,type:visualization),(col:7,id:git_commits_timezone,panelIndex:2,row:9,size_x:6,size_y:2,title:%27Commits%20by%20Time%20Zone%27,type:visualization),(col:2,id:git_evolution_authors,panelIndex:3,row:3,size_x:5,size_y:2,title:Authors,type:visualization),(col:2,id:git_evolution_commits,panelIndex:4,row:1,size_x:5,size_y:2,title:Commits,type:visualization),(col:7,id:git_evolution_organizations,panelIndex:5,row:5,size_x:6,size_y:4,title:Organizations,type:visualization),(col:1,id:git_main_numbers,panelIndex:6,row:1,size_x:1,size_y:4,title:Git,type:visualization),(col:1,id:git_organizations_table,panelIndex:7,row:9,size_x:6,size_y:5,title:Organizations,type:visualization),(col:1,id:git_top_authors,panelIndex:8,row:5,size_x:6,size_y:4,title:Authors,type:visualization),(col:10,id:git_top_projects,panelIndex:9,row:1,size_x:3,size_y:4,title:Projects,type:visualization),(col:7,id:git_top_repositories,panelIndex:10,row:11,size_x:6,size_y:3,title:Repositories,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:%27*%27)),title:Git,uiState:(P-1:(title:Organizations),P-10:(title:Repositories,vis:(params:(sort:(columnIndex:!n,direction:!n)))),P-2:(title:%27Commits%20by%20Time%20Zone%27,vis:(legendOpen:!f)),P-3:(title:Authors,vis:(legendOpen:!f)),P-4:(title:Commits,vis:(legendOpen:!f)),P-5:(title:Organizations),P-6:(title:Git),P-7:(title:Organizations,vis:(params:(sort:(columnIndex:!n,direction:!n)))),P-8:(title:Authors,vis:(params:(sort:(columnIndex:!n,direction:!n)))),P-9:(title:Projects,vis:(params:(sort:(columnIndex:!n,direction:!n))))))) to production server with the filter in place.
