### ISSUE TITLE
Emerging Technologies Dashboard

### ISSUE THREAD

**Issue by dicortazar** [mozilla/participation-metrics-org#121]
This ticket contains information related to the emerging technologies dashboard, requirement discussion, and others.

# First Iteration for the Emerging Technologies Dashboard

The first version is available at https://analytics.mozilla.community/edit/app/kibana#/dashboard/Emerging-Technologies

## Context and Data Sources
Two projects are considered for this panel: Rust and A-Frame. Rust contains the repositories rust-lang/rfcs and rust-lang/rust. While the A-Frame project analyzes the repository aframevr/aframe.

The information is a view or a subset of the information found in the general Git and GitHub repositories for the Community Analytics Mozilla dashboard. This means that any change in those repositories affects the results in this panel.

## Panel
The panel is divided into four main sections. The top section contains summarized information for each of the data sources. While the rest of the panel is splitted by data source in this order: Git, GitHub Issues and GitHub Pull Requests.

### Summary section
This contains the following widgets:
* Git: summary of Git activity.
* GitHub PRs: summary of Pull Requests activity.
* GitHub Issues: summary of GitHub issues activity.
* Projects: table that can be used for filtering. This panel provides metrics for all of the projects aggregated and those metrics can be drilled down by project (or potentially by any clickable widget). This helps to focus at the granularity of the project.
* Organizations: Pie chart that provides information about the organizations involved in the development of the selected projects. This widget can be drilled down to look for specific info by any of the organizations. As a side note, any of the filters can be mixed, so we could look for information of the Rust project and done by the Community at some point.
* Domains: table that contains the list of domains that are part of the Git development activity. This is expected to help to understand what other organizations are involved in the Community part of the project. This could be done by clicking on the Organizations widget -> Community section. Then the whole panel will filter all of the displayed information by that new filter.

### Git Activity section
* Git Authors: evolution of the authors over time (those authoring pieces of code).
* Commits by Time Zone: geographical area of the developer commits (by UTC).
* Commits: evolution of the activity over time.
* Git Authors: top authors by number of commits, added and removed lines.
* Git New Contributors: last contributors adding the organization, the date for the first commit and the current number of commits.
* Git Repositories: list of repositories by number of commits and authors.

### GitHub Issues section
* GitHub Issue Status: evolution of the issues open and closed over time. This represents for a given period the number of open issues at that point and from those, the number of closed tickets.
* GitHub Issues Submitters & Assignees (Workload): evolution of issue submitters and developers being assigned an issue. This helps to understand the workload adequacy of the developers. Other charts could be developed to work with relative numbers if needed.
* Issue Submitters: top issue submitters together with the mean time to close their issues.
* Issue Labels: list of labels used in each of the tickets.

### GitHub Pull Requests section
* GitHub PRs Submitters & Assignees (Workload): evolution of pull request submitters and developers being assigned an issue. This helps to understand the workload adequacy of the developers. Other charts could be developed to work with relative numbers if needed.
* GitHub Pull Request Status: evolution of the pull requests open and closed over time. This represents for a given period the number of open pull requets at that point and from those, the number of closed ones.
* Pull Request Submitters: top pull request submitters together with the mean time to close their pull request.
* Pull Request Labels: list of labels used in each of the pull requests.

**Comment by hmitsch** [comment]
@HerminaC can we close this issue?

**Comment by HerminaC** [comment]
Yes we can. Thanks!

**Comment by dicortazar** [comment]
I think we can close this then :)

**Comment by techtonik** [comment]
Gives 500 error. Is it public?

**Comment by hmitsch** [comment]
@techtonik sorry for the error. Indeed the dashboard is not public. It is targeting Mozilla Staff + NDA’ed Volunteers.

-Henrik

**Comment by techtonik** [comment]
NDA'ed Volunteers? I thought Mozilla is an open source organization.

**Comment by hmitsch** [comment]
@techtonik,
of course you are right. Mozilla is an open source organization. 

The Community Analytics dashboards contain some sensitive records: we have data on Staff tenure in order to attribute contributions to Staff or volunteers. 

For this reason access is currently restricted. 

If you want me to provide you with a screenshot of the Emerging Technologies contribution dashboard, I can get you one next week.

Regards,
   Henrik

**Comment by techtonik** [comment]
I don't understand why Staff tenure data is so sensitive? I've never seen that information that some person is working for some company is a secret. Dashboard is interesting - to see if there is any gameplay in that.

**Comment by techtonik** [comment]
Another point of interest is that I am also interested in crediting people in various open source projects. For example - https://sourceforge.net/p/roundup/code/ci/default/tree/scripts/contributors.py And there is no that time on my side to do all the stuff myself. There is no tenure for millenials, you know. )
