### ISSUE TITLE
Discourse: can we make `body_extract` searchable in edit mode?

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#125]
Mail exchange with @alpgarcia:

> body_extract
> A couple of weeks ago there was a body_extract field for Discourse which included the entire message body. This is gone now. So here are my questions:
> a) can we re-introduce this field?
> b) can we make it searchable (indexed)?

This field is not used in the widgets and it seems it is not in the index definition. Thus, it was there as a part as an old index version. As I would need to ask our dev team to include them, could you please create a ticket to keep track on this?

**Comment by alpgarcia** [comment]
Our estimation is including the change in the next week GrimoireELK release, i.e., Thu. Sep 21.

Once included, it will be a matter of updating the index (it should be a couple of hours once our DevOps team is aware of the update and find a slot to do it).

**Comment by acs** [comment]
Hi @hmitsch !

After some research, I think that the body_extract is a field that you have found in NNTP data source (which share the same implementation than mbox).

https://github.com/grimoirelab/GrimoireELK/blob/master/grimoire_elk/elk/mbox.py#L154

In discourse this field has never existed before. Analyzing the raw discourse items, there is no field with a similar name. The most similar one is the field "cooked" with the contents of the question or answer, but in HTML.

Do you want that we include this field?

Cheers!

**Comment by hmitsch** [comment]
Oh man, I feel totally embarrassed now ... A similar mix-up of things has happened to me recently with two different providers of Slack bots ... so, so, so sorry!! I will quickly hide under a rock and be back in a few moments when I am done with this terrible feeling of embarrassment.

**Comment by LeoMcA** [comment]
Not sure what API endpoint you're using, but there's a few from which you can get the raw contents of posts:

[`/t/{topic_id}.json?include_raw=1`](https://discourse.mozilla.org/t/2980.json?include_raw=1)
[`/raw/{topic_id}/{post_number}`](https://discourse.mozilla.org/raw/2980/1)
[`/posts/{post_id}/raw`](https://discourse.mozilla.org/posts/9008/raw)

**Comment by hmitsch** [comment]
Hi @acs,

I am done with feeling embarrassed and ready to take another stab at formulating the desired outcome.

**Discourse:**
* Can we add one of the `raw contents feeds` from the previous post to retrieve and index Discourse articles?

**NNTP Data:** (mbox implementation)
* Can we **index** the field `body_extract`?

Best regards,
   Henrik

**Comment by acs** [comment]
@LeoMcA right now we have a field with the content of the post (or the answer) in a "cooked" field. The issue is that it is HTML formatted. @hmitsch this could be enough for your needs or do you need the raw contents?

About the body_extract field, we are indexing right now the first 10 lines to avoid issue with pretty long bodies in the messages. Do you need the full text of then body?

**Comment by hmitsch** [comment]
Well, we wanted to search for mailing list posts (newsgroup items) which contain a reference to a bug. The way we intended to do that was to search for an URL fragment of Bugzilla in the `body_extract`. 

This means that the first 10 lines are probably not enough. 

I guess there are some conceptional thinking errors in our approach. What do you suggest to do?

**Comment by LeoMcA** [comment]
If we're searching for references to a bug using a URL fragment, there should be no problem using cooked rather than raw.

**Comment by jgbarah** [comment]
Could you share what you intend to do, so that we have more clues? Maybe it is better to work with the raw index, instead of the enriched one. Have in mind that every time we add data to the enriched one, it needs later to be maintained for the dashboard. (Not saying that this is not the best thing to do here, just wondering...)

**Comment by hmitsch** [comment]
Closing issue as WONTFIX.
