### ISSUE TITLE
Shortened links to Community Analytics return  HTTP 502 (Bad Gateway)

### ISSUE THREAD

**Issue by acs** [mozilla/participation-metrics-org#126]
@hmitsch reported that:

«Why do I get HTTP 502 (Bad Gateway) when I try to open the shortened links to Community Analytics?

Example: https://analytics.mozilla.community/goto/5a03461860d1bceba0ef6885e58c75bc
I don't understand ... the below quoted URL works ... whyyyy?

https://analytics.mozilla.community/goto/a3c430c36d31bb3f4dc550ea4d787816»

**Comment by acs** [comment]
Hi @hmitsch!

Bug fixed. 

There was an issues with the HTTP headers returned by Kibana in some cases. These headers was too large for the default nginx config and we need to increase it.

Basically:

```
location / {
...
                proxy_buffer_size   128k;
                proxy_buffers   4 256k;
                proxy_busy_buffers_size   256k;
        }
```

Now you can use the short url failing:

https://analytics.mozilla.community/goto/5a03461860d1bceba0ef6885e58c75bc

Probably we can close now this issue!

**Comment by hmitsch** [comment]
This is awesome. Thank you!
