### ISSUE TITLE
Allow Henrik to run get_uuids_from_emails.py

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#136]
* Access Community Analytics server(s) via SSH
* Add a **read-only** user to SortingHat's MariaDB
* Validate tooling README.md (python virtual environment)
* Fun!

**Comment by sanacl** [comment]
@hmitsch these are the steps:

1. access to the server (IP sent via private message). I'll need your SSH public key (RSA) to give you access

2. activate the virtual env (local python packages installed there)
```
$ source ~/venvs/elastic-env/bin/activate
(elastic-env) $ cd mozilla-contribution-analysis/data-analysis/tools/
```

3. example of use for your email
```
(elastic-env) $ cat /tmp/input 
email
hmitsch@mozilla.com

(elastic-env) $ python3 get_uuids_from_emails.py -i /tmp/input -o /tmp/output                                        
Reading email blacklist from SH                
Searching for E-Mails in SH...                 
22633  entities read from SH                   
Creating E-Mails dict...                       
Done! Entities in emails dict:  30040  Dups:  307                                              
30040  emails read from file                   
dups in csv: 0                                 
Not found: 0                                   
Found         :  1                             
Found (unique):  1                             
Writing results...                             
Results wrote to file  /tmp/output             
This is the End. 
```

**Comment by sanacl** [comment]
@hmitsch got access to the server. 

If the process above detailed is not working please reopen.

**Comment by hmitsch** [comment]
For reference, the UUID script is here: https://github.com/mozilla-parsys/mozilla-contribution-analysis/blob/master/data-analysis/tools/get_uuids_from_emails.py

**Comment by hmitsch** [comment]
Script works like a charm. Thank you!
