### ISSUE TITLE
Change MySQL instance configuration

### ISSUE THREAD

**Issue by albertinisg** [mozilla/participation-metrics-org#138]
I've been digging into the logs and found that we are getting errors while running some queries. This happened to us few times, and it's due to some timeouts. The values that worked for us are the following:
```
wait_timeout=2592000
interactive_timeout=2592000
max_connections=300
```
@hmitsch can you help us find who is the person that can help us with this?

**Comment by hmitsch** [comment]
As far as I understand @sanacl is configuring these things?

-Henrik

**Comment by sanacl** [comment]
@hmitsch nope, the relational database we are using is an AWS service.

**Comment by hmitsch** [comment]
Aaah, in this case we probably need @flamingspaz's help?

**Comment by flamingspaz** [comment]
Opened https://github.com/mozilla/partinfra-terraform/pull/171

`max_connections` is already set to over 300.

**Comment by flamingspaz** [comment]
the new parameters are applied to the database now, let me know if you still have issues.
