### ISSUE TITLE
Meetup data is not updated 

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#143]
Meetup data was updated on "November 23rd 2017, 01:01:17.959" so it has not been updated in 5 days.

It could be partially related to the migration as the data collection was not enabled until yesterday (Mon 27th) noon. This ticket will be closed when a clear explanation of what is happening is provided.

Version: `elasticgirl.22`

**Comment by sanacl** [comment]
The data collection is still in progress, the app is up & running so I discard that it is not being updated due to a bug. What seems to be happening here is that the data collection is so slow (due to rate limitations) that the enrichment process has not started yet (and the process was launched 24 hours ago). Due to the current workflow, the tools waits until data for all the meetups is stored, then it produces the enriched data (used by the dashboard).

I'm leaving this open to identify what is the current delay updating data.

CC @hmitsch @dicortazar

**Comment by sanacl** [comment]
Meetup data was updated yesterday. So it is taking almost two days to get updated. I'll leave this open to confirm once again this is what is happening.

**Comment by sanacl** [comment]
Meetup data was updated yesterday. So it is taking almost two days to get updated. I'll leave this open to confirm once again this is what is happening.

**Comment by sanacl** [comment]
@albertinisg I see data is updated for Meetup. Before closing, can you please confirm everything is ok here?

**Comment by albertinisg** [comment]
We are having issues with the new perceval client. I need to wait for the fix https://github.com/grimoirelab/perceval/issues/244 and check after that to make sure we retrieve everything.

**Comment by sanacl** [comment]
I'm ok with this blocker @albertinisg but if this is not working it means we are slower getting data, but as far as I see without losing data (which is the important thing). In any case let's review this again when the blocker is solved.

Status:
* pending rewiew, it will be done when https://github.com/grimoirelab/perceval/issues/244 is fixed

**Comment by albertinisg** [comment]
We are still struggling with the retrieval. A new bug has appeared:

https://github.com/grimoirelab/perceval/issues/261

**Comment by sanacl** [comment]
Data collection was fixed. Data is updated at last.
