### ISSUE TITLE
Broken Bugzilla panel

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#144]
After migration to Kibana 5 the Bugzilla panel is broken.

![screenshot](https://user-images.githubusercontent.com/326719/33323980-65afa6c4-d44e-11e7-9874-629955a8b3e2.jpeg)

current version deployed: `elasticgirl.22`

**Comment by dicortazar** [comment]
Regarding to the warning strings, it seems that the panel is using the 'creation_date' field instead of the 'grimoire_creation_date'. This sounds like a bug to me, but we should have a look carefully.

**Comment by sanacl** [comment]
@dicortazar we have a patch for this in our internal ticket T4611. You can get there low-level detail if you want.

**Comment by sanacl** [comment]
Patch already merged: https://github.com/grimoirelab/GrimoireELK/pull/136

**Comment by dicortazar** [comment]
@sanacl thanks for the pointer. In any case we should be using the grimoire_creation_date as date by default everywhere, I'll annotate this in that ticket.

**Comment by sanacl** [comment]
@acs added a workaround to get `Bugzilla` panel working. In order to fix the real issue we need to get a fresh version of the enriched index and update the latest version of the Bugzilla panels.

Tomorrow morning we'll have a version of the index. If everything goes well the bug will be solved by tomorrow. Stay tuned.

**Comment by sanacl** [comment]
The new index has 50% of the documents enriched. It still needs a few hours.

**Comment by sanacl** [comment]
Data is ready, `Backlog` panel still broken.

**Comment by sanacl** [comment]
The new panels need a field included by the version f614d5c4c0fd52b763aec2b472fcb9f82ec751db so we need to update the index once again. 😿 

ETA: We need two more days for this.

**Comment by hmitsch** [comment]
Feels like Groundhog Day ...

**Comment by sanacl** [comment]
This task is blocked by https://github.com/grimoirelab/panels/pull/146

@dicortazar can you unblock this?

**Comment by sanacl** [comment]
Task is unblocked.

**Comment by sanacl** [comment]
Latest Bugzilla panels uploaded. Data up to date.

We are done.

**Comment by hmitsch** [comment]
Confirmed. Thank you!
