### ISSUE TITLE
Ghost organization (no name) in our organizations chart

### ISSUE THREAD

**Issue by zhquan** [mozilla/participation-metrics-org#145]
![firefox_screenshot_2017-11-30t10-09-34 288z](https://user-images.githubusercontent.com/5637233/33426634-db6b41b4-d5c2-11e7-9afd-821b88488af1.png)

**Comment by sanacl** [comment]
It seems to be related with some encoding errors while adding people to our identities database. A couple of identities were affected so as soon as the bug is fixed, those ids will be updated (to reflect the real affiliation).

**Comment by sanacl** [comment]
This error affects a couple of git authors. It is ugly but the impact on the data quality is minimum.

**Comment by sanacl** [comment]
This ticket should be fixed. Sorry for the delay. I'll push to fix it during this week.

**Comment by sanacl** [comment]
We have around 500 commits affiliated to 'None'. We are fixing the tool needed to fix this 🤕

**Comment by sanacl** [comment]
@acs I tried refreshing the whole index and this is still happening.

**Comment by sanacl** [comment]
Feedback from Bitergia developers. They are working on this as part of the Bitergia product. In some cases the author information is empty:
* example: https://github.com/m3db/m3/commit/01a2adea0e582baeddedd385ff626d6f02ad3e45?diff=unified

They are working on providing a solution for this.

**Comment by mafesan** [comment]
Hi, 

This issue is now solved and it will be included in the next release of the platform. We will update this issue again once https://http://analytics.mozilla.community/ gets upgraded to the newest version.

**Comment by hmitsch** [comment]
Solved with upgrade to Kibana 6 (latest GrimoirLab package).
