### ISSUE TITLE
Update GitHub repo list + project grouping (03 DEC 2017)

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#146]
Update [GitHub repo list + project grouping](https://docs.google.com/spreadsheets/d/1xFrt9JZkZ6m8peasYaRfPO5kC1JDo-vDJJuYfMwcGqM/edit) (03 DEC 2017)

Can we please have this **ASAP** because some of our stakeholders would like to work with this data at the All Hands on DEC 11 2017.

**Comment by sanacl** [comment]
Data is being analyzed. I'll update the ticket with a link as soon as data is available on the dashboard.

**Comment by sanacl** [comment]
Git data:
* Web Compatibility: https://mozilla5.biterg.io/goto/8b39c2814727a448b39e01904c48d4c4
* Developer Tools: https://mozilla5.biterg.io/goto/a6b4b5677f7c68c97c1b48b46983a667

Github data blocked by ticket: #147 (ETA for the fix. Today EOB)

**Comment by sanacl** [comment]
Github data:
* Web Compatibility: https://mozilla5.biterg.io/goto/4cd681d1e8f5122a6a166d6ffc2edb69
* Developer Tools: https://mozilla5.biterg.io/goto/fddfc6cf93dff8550986fcfc87b010c0

This is done @hmitsch
