### ISSUE TITLE
Missing `author_domain` for some commits in Git

### ISSUE THREAD

**Issue by alpgarcia** [mozilla/participation-metrics-org#150]
There are some cases in `Emerging Tech` panel where we have more commits by domain for `areas of code` than for summary table. In particular this happens for gmail. It seems like it affects to ~50 commits (upper bound):
https://mozilla5.biterg.io/edit/goto/503c866d0da7a4d1cb86a25859be13cf

Though unique counts are not always accurate in ES (depends on [`precision_threshold`](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/search-aggregations-metrics-cardinality-aggregation.html#_precision_control), set to 3000 by default), with small numbers, both should match even using unique counts.

What I did to check numbers was modifying both tables (summary and areas of code) to show commit hashes. I looked for a small time frame with number discrepancy and I found one between 26th-27th Oct. 2017. I found counts were accurate in those cases: 5 commits for summary table, 6 commits for areas of code. So, at least in this case, unique counts are accurate.

I had a look at the commits and I found the problem. Git index is missing author domain for one of them:
https://mozilla5.biterg.io/edit/goto/db44d18ac99bc3ff7179a0fc7901de3c

In areas of code, created today, both commits do have gmail domain:
https://mozilla5.biterg.io/edit/goto/4e730c73ceeb17bc47625157764f3fd1

**Comment by acs** [comment]
Working on it ... once I found the reason I will post if here and I will try to fix it. Stay tuned!

**Comment by acs** [comment]
The main issue here is that the current domain for a user in enriched indexes comes from her profile from SortingHat. The profile is linked to a unique identity, which can have identities from several data sources, and from these identities the email could be different.

So for a unique identity, several emails can be present. One of them, not in a fixed way, is selected to get the domain for the profile. So the domain data is not very robust to build analysis around it.

In this case, probably the fix is to have another domain field with the domain found in the email in the git commits, a git_domain field. And then, use this field for filtering of the data. This solution is **git** specific, so it can be used only with git data.

Does this solution fix the issues around domains analysis for you? I think so.

I am sorry about the one month delay for this issue. It got out of my radar :(

**Comment by hmitsch** [comment]
Hi @acs,

thanks for following up. Great to hear about the solution you proposed. What's your estimate on when this can be delivered?

Best regards,
   Henrik

**Comment by sanacl** [comment]
We'll reply you during the next working hours. Sorry for the silence.

**Comment by acs** [comment]
@hmitsch I am working on it right now. Once we have this new field (the domain for the author of the commit) in the enrich indexes, we need to use it in the panels.

**Comment by acs** [comment]
The new field is already available in the enriched index. So we just need now to start using it in the panels.

**Comment by alpgarcia** [comment]
Actually we also need to update the areas of code enrichment process to include it. It should be a 1 day task, including updating the index and panels.

I'm scheduling this for our current sprint, ending on Feb. 18th just in case we have some "free" time available. We will probably need to re-schedule it for next one.

**Comment by alpgarcia** [comment]
Quick update on the progress: we are currently working on a PR that includes side functionalities aiming at  easing the way we add new studies (like onion, gender and areas of code), which basically means using cereslib project in grimoire-elk.

Once it is done ans tested in grimoire-elk, then cereslib will be updated to include the new field.

**Comment by alpgarcia** [comment]
Pull requests to support this feature are waiting from review (more details in the following grimoirelab-elk issue):
https://github.com/chaoss/grimoirelab-elk/issues/174#issuecomment-371864410

Next steps: update areas of code data once these PRs are merged and released.

**Comment by sanacl** [comment]
@alpgarcia @acs can u please provide more info? We need an ETA here :)

**Comment by sanacl** [comment]
The code is accepted upstream. Changes will be in production after next weekly release is published.

**Comment by hmitsch** [comment]
Expected for release in 18.03 or 18.04.

-Henrik

**Comment by sanacl** [comment]
Generating new index. We'll evaluate tomorrow morning whether the fix worked.

**Comment by sanacl** [comment]
Git index generated with 18.03-04 is ready. Waiting for @alpgarcia's confirmation before publishing it.

```
>> indexwarrior mozilla index compare git_mozilla_180206_enriched_180206 git_mozilla_180206_enriched_180404
+----------------------+----------------------------------------------+----------------------------------------------+
| data/index           | git_mozilla_180206_enriched_180206           | git_mozilla_180206_enriched_180404           |
+----------------------+----------------------------------------------+----------------------------------------------+
| docs                 | 4489816                                      | 4490365                                      |
|                      |                                              |                                              |
| metadata__timestamp  | 2018-04-04T12:20:21.264Z                     | 2018-04-04T16:28:52.608Z                     |
|                      |                                              |                                              |
| metadata__updated_on | 2018-04-04T11:51:35.000Z                     | 2018-04-04T16:19:07.000Z                     |
|                      |                                              |                                              |
| affiliation          | Mozilla Staff: 2797876                       | Mozilla Staff: 2798309                       |
|                      | Community: 1518816                           | Community: 1518899                           |
|                      | Code Sheriff: 159624                         | Code Sheriff: 159652                         |
|                      | Mozilla Reps: 8407                           | Mozilla Reps: 8412                           |
|                      | Functional Reps: 4655                        | Functional Reps: 4655                        |
|                      | : 438                                        | : 438                                        |
|                      |                                              |                                              |
|                      |                                              |                                              |
| origin               | ..//github.com/mozilla/gecko-dev.git: 659979 | ..//github.com/mozilla/gecko-dev.git: 660097 |
|                      | ..hub.com/mozilla/gecko-projects.git: 653076 | ..hub.com/mozilla/gecko-projects.git: 653172 |
|                      | ..://github.com/mozilla/positron.git: 505100 | ..://github.com/mozilla/positron.git: 505152 |
|                      | ../github.com/mozilla/newtab-dev.git: 470416 | ../github.com/mozilla/newtab-dev.git: 470465 |
|                      | ..lla/universal-search-gecko-dev.git: 418865 | ..lla/universal-search-gecko-dev.git: 418901 |
|                      | ..//github.com/mozilla/spiderweb.git: 323944 | ..//github.com/mozilla/spiderweb.git: 323945 |
|                      | ..rvices/services-central-legacy.git: 104494 | ..rvices/services-central-legacy.git: 104505 |
|                      | ..b.com/rust-lang/crates.io-index.git: 88915 | ..b.com/rust-lang/crates.io-index.git: 88926 |
|                      | https://github.com/rust-lang/rust.git: 78578 | https://github.com/rust-lang/rust.git: 78581 |
|                      | ..s://github.com/mozilla-b2g/gaia.git: 64968 | ..s://github.com/mozilla-b2g/gaia.git: 64968 |
|                      |                                              |                                              |
|                      |                                              |                                              |
+----------------------+----------------------------------------------+----------------------------------------------+
```

**Comment by sanacl** [comment]
New git index applied but I see at [1] six contributors with empty git_author_domain. The release used to generate this index was 18.03-04. Is this a bug @alpgarcia @acs ? If so, is this solved with 18.04-01? Generating indexes for Mozilla is not trivial (it takes more than 12 hours) so I won't blindly do it unless you tell me this will be fixed.

[1] https://analytics.mozilla.community/edit/goto/664fcb6cb04b8c3b7e93e11c0fa152c8

**Comment by alpgarcia** [comment]
This is not a bug, we just don't get any domain available within commit data. In those cases `Author` field does not have any domain. For instance, looking one random commit from above's link and looking for its hash in the RAW index, we can find `data.Author=Kalervo Kujala <kkujala@>` [2], i.e., no domain. 

[2] https://analytics.mozilla.community/edit/goto/5244086c9d93888b44cb2484e5c0b4a1

**Comment by sanacl** [comment]
@alpgarcia @acs Great news, we are done then. The new field git_author_domain is right.

Closing ticket ..
