### ISSUE TITLE
Performance issues with the dashboard

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#152]
We've just got this feedback from one or the members of the Mozilla team:

```
Unfortunately the dashboard seems to have some problems as it just loads
forever (screen with ''give me a minute, I'm loading a bunch of code" seems
frozen). 
 .. 
(tried in both FF and Chrome, also restated computer but
still didn't work).
```

**Comment by sanacl** [comment]
We need to discard this is a memory issue, so I'm asking Hermina when this happen. I'll need your help to see the resources used by the server @flamingspaz

**Comment by flamingspaz** [comment]
AWS doesn't store historical data for memory usage, only CPU and network (which look fine)
```
             total       used       free     shared    buffers     cached
Mem:           60G        59G       330M       179M       185M        54G
-/+ buffers/cache:       4.9G        55G
Swap:           0B         0B         0B
```

**Comment by sanacl** [comment]
Copy that @flamingspaz . I'll ask my team about more data.

The time this behaviour was spotted on Jan 30th from 17h50 to 20h00 CET

**Comment by hmitsch** [comment]
Closing because we don't have any data to analyze this right now. Let's create a new issue if/when this issue happens again.
