### ISSUE TITLE
Update GitHub repo list + project grouping (07 FEB 2018)

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#153]
Please update [GitHub repo list + project grouping](https://docs.google.com/spreadsheets/d/1xFrt9JZkZ6m8peasYaRfPO5kC1JDo-vDJJuYfMwcGqM/edit) (07 FEB 2018)

**Comment by hmitsch** [comment]
Reason for the request: https://github.com/mozilla-l10n/pm-projects/issues/117

**Comment by acs** [comment]
Working in it ...

**Comment by acs** [comment]
Done in: https://github.com/Bitergia/projects-mozilla/commit/3426f02cc565e580d73cdb8ea661ee36b3bef742

In the next hours the repositories will be available in the dashboard. Once they appear we can close this ticket.

**Comment by nukeador** [comment]
Great, can you ping us here once the data is available? Thanks!

**Comment by acs** [comment]
Sure @nukeador . Once I confirm they are included, I will ping you using this ticket so we can close it :)

**Comment by sanacl** [comment]
This was already done. Closing @nukeador  ..
