### ISSUE TITLE
Crates data is not updated due to KeyError with 'email'

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#154]
There is a bug in the Crates enrichment. Data collection is working properly according to the logs. The result is data is not updated on the dashboard.

Version: elasticgirl.30

```
admin@ip-10-0-93-34:/data/docker/containers/mordred/mozilla$ zcat /data/docker/logs/mordred/mozilla/all.log.2.gz |grep crates|grep -v github.com|grep ERROR
2018-02-06 17:18:52,835 - grimoire_elk.elk.elastic - ERROR - Failed to insert data to ES: {'reason': 'Limit of total fields [1000] in index [crates_mozilla_171205_1] has been exceeded', 'type': 'illegal_argument_exception'}

2018-02-06 19:33:01,744 - grimoire_elk.arthur - ERROR - Error enriching ocean from crates (https://crates.io/): 'email'
```

I guess that we have two bugs here, the first one because of the mapping, the second one due to a KeyError. If you confirm that I would open a new one for the mapping.

Projects.json file at: https://github.com/Bitergia/projects-mozilla/blob/master/projects.json

**Comment by acs** [comment]
We have the fixes ready to be introduced in the platform and to be deployed. So during the next week this issue must be fixed.

**Comment by sanacl** [comment]
@acs we need a new ETA here please, the "next week" we said in previous comment expired ;)

**Comment by acs** [comment]
> @acs we need a new ETA here please, the "next week" we said in previous comment expired ;)

The publishing of the new version of the grimoirelab platform has been done:

https://github.com/chaoss/grimoirelab/blob/master/releases/NEWS

so once it is deployed in mozilla env, the issue must be fixed.

**Comment by sanacl** [comment]
According to what @acs said, the ETA for this is this Friday

**Comment by sanacl** [comment]
According to what @acs said, the ETA for this is this Friday.

**Comment by sanacl** [comment]
The fix is applied so this task is now blocked by the deployment of the new version. This is a work in progress and should be done between today and next Tuesday.

**Comment by sanacl** [comment]
New version deployed with the fix. We still have to confirm the error is gone.

**Comment by sanacl** [comment]
This issue was solved.
