### ISSUE TITLE
Wrong data for Bugzilla in production since November 30th 2017

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#155]
Hi all,
this message is **important/urgent**. 

My team has identified wrong data being published for the Bugzilla panels. The bug produced an error of **99.06%** in the enriched Bugzilla index, the wrong data was published after November 30th 2017 and was show on the dashboard until (today) February 12th.

The data used by the reports done during last summer is **not affected by this bug**. What could be affected is every data from Bugzilla related to tickets. The count of contributors should not be affected due to this is a unique count performed over the data.

During the next minutes we are deploying a new version of the index which fixes the error. The bug was identified in the software that converts the spreadsheet to the projects JSON file and it is already fixed.

We are open to any question you may have. Sorry for any inconvenience, the Bitergia team.

**Comment by hmitsch** [comment]
Thanks for the update and the explanation. That's great. 

Onwards,
   Henrik

**Comment by sanacl** [comment]
After the fix was applied, the number of documents collected in the raw index and the number of enriched documents are the same. We can close this and focus on the bugs found with the categorization of the Bugzilla documents (ticket ·#149)

So @hmitsch , from my point of view this ticket can be closed.
