### ISSUE TITLE
Update repo list + project grouping (26 FEB 2018)

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#159]
The set of repos monitored must be updated according to latest changes in the spreadsheet at https://docs.google.com/spreadsheets/d/1xFrt9JZkZ6m8peasYaRfPO5kC1JDo-vDJJuYfMwcGqM/edit

Changes are requested by Hermina Condei

**Comment by sanacl** [comment]
New repos should be available during next 12 hours. When they are displayed on the dashboard I will manually remove the repos deleted from the JSON file.

**Comment by hmitsch** [comment]
Done.
