### ISSUE TITLE
Track Activate Metrics

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#16]
Currently we are gathering campaign metrics here (mostly manually):

https://docs.google.com/spreadsheets/d/1ss3nkmIIYYFLjvBfROB8-p2xB4HRAVTm5t323e_vhsk/edit?pli=1#gid=2122840069

I'm wondering if it makes sense to import from that spreadsheet into the dashboard.

**Comment by acs** [comment]
Right now we are supporting the spreadsheet for Mozilla Club Events. Is it the same? If not, it is possible to do it following a similar approach.

**Comment by hmitsch** [comment]
Requirement discarded in collaboration with @brianking. It is our aim to create the above mentioned Google spreadsheet in the Community Analytics platform. This is preferred over connecting a manually populated data source to Community Analytics.
