### ISSUE TITLE
Add Slack to the Community Analytics Menu

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#160]
This request is related to one of the work items in the Q1/2018 SOWs.

We created a new tab in the Project Grouping sheet and added 2 Slack channels. The (temporary) Dashboard looks great.

Let's add this to the regular Menu to make it easily discoverable.

**Comment by sanacl** [comment]
This is done

![firefox_screenshot_2018-03-09t17-14-46 339z](https://user-images.githubusercontent.com/326719/37220076-c6eb10ce-23c5-11e8-9280-75fb1c5220ea.png)

**Comment by hmitsch** [comment]
Nice, thank you!
