### ISSUE TITLE
Wrongly project assignation for certain commits in the same repository

### ISSUE THREAD

**Issue by dicortazar** [mozilla/participation-metrics-org#165]
### How to reproduce the issue:

* https://analytics.mozilla.community/goto/7caab5ed1dcbcf76679b23e1aed7967e

How to reproduce the issue from scratch:
* Go to EmTech -> Development
* Click on https://github.com/xiph/rav1e.git repository
* Some of the commits are assigned to Daala while some others are assigned to Unknow.

As the information for EmTech is a subset of the information in Git, that can be reproduced in the same way in the general Git panel: https://analytics.mozilla.community/goto/01e7a60aee44112b1404c322d802a86a

**Comment by dpose** [comment]
@dicortazar @hmitsch @HerminaC 

It is already fixed! :+1:  
EmTech panel -> https://analytics.mozilla.community/goto/7caab5ed1dcbcf76679b23e1aed7967e
Git panel -> https://analytics.mozilla.community/goto/01e7a60aee44112b1404c322d802a86a

**Comment by hmitsch** [comment]
Excellent, thank you!
