### ISSUE TITLE
Project support in Twitter

### ISSUE THREAD

**Issue by dicortazar** [mozilla/participation-metrics-org#166]
The only project available for Twitter as we can see at https://analytics.mozilla.community/app/kibana#/dashboard/Twitter is 'Main'.

However this is wrong according to the list of projects defined by @hmitsch and Hermina.

**Comment by sanacl** [comment]
This is DUP. See #163

**Comment by dicortazar** [comment]
Ok, closing this, sorry!

Thanks for the pointer.
