### ISSUE TITLE
IRC is not updated

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#173]
According to the panel, the IRC data is not updated. According to the maximum value of metadata__timestamp it is ... something is broken here and breaks the checks we have to ensure data is collected. 

High priority.

**Comment by sanacl** [comment]
Hi @hmitsch ,
we have two issues here:

    enrichment is was not working (should be solved during next working hours)
    we've lost data from March 28th to April 6th, it is not possible to collect that data using the Twitter API

Hi @hmitsch,
the IRC data collection was broken until April 26th. Due to a strange software error in our side the latest items we had collected (from April 1st) were being overwritten and the field we use to check whether data is being refreshed was telling us everything was ok when the reality was we were losing data. The data collection started to fail on April 1st when the bot we use to collect data from Mozilla exited from your channels without being able to enter again. As a consequence we have lost IRC data for the period of time between April 1st and April 26th. That means you'll see an awful gap in your data. :cry: 

We would like to refund part of the subscription fee as we did with the previous error. Please let's talk privately about this.

**Comment by hmitsch** [comment]
Hi @sanacl, thanks for the update. Let's close this issue as the data is updated again.

Best regards,
   Henrik
