### ISSUE TITLE
Hatstall beta access

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#175]
Currently expecting access around the second half of June 2018.

**Comment by sanacl** [comment]
We will deploy it ASAP with admin access for Henrik.

The url will be https://analytics.mozilla.community/identities

**Comment by sanacl** [comment]
I've found some configuration errors related to django and how the SSL connection is redirected. I have to talk to the developers to fix this. Sorry for the delay :turtle: 

> Forbidden (403)
> 
> CSRF verification failed. Request aborted.
> 
> You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.
> 
> If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.
>

**Comment by sanacl** [comment]
The CSRF thing is solved. Our developers found an error related to the big size of the identities database. The Hatstall page where the search form is displayed is doing a query to the SQL which is receiving a connection timeout (due to the database size I guess) and it crashes. They are working on it.

**Comment by hmitsch** [comment]
Thanks for the update. Highly appreciated.

**Comment by hmitsch** [comment]
Status update (from our weekly call): Bitergia devs are still working on making Hatstall with Mozilla's rather giant identity database. Currently, timeouts are being addressed.

URL will be: https://analytics.mozilla.community/identities

Best regards,
   Henrik

**Comment by mafesan** [comment]
Hi @hmitsch , 

Our Dev team has finally solved the timeouts issue. Now, you have Hatstall fully enabled with admin access at: https://analytics.mozilla.community/identities

Please, let us know if you have any question or issue. Thank you!

Best, Miguel-Ángel

**Comment by hmitsch** [comment]
It works, niiiiice!

https://screenshots.firefox.com/SWPgDqZbAHNxSBgU/analytics.mozilla.community
