### ISSUE TITLE
Create OSSN Organization

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#178]
Hi @sanacl,

similar to _Organizations_ such as `Mozilla Reps` and `Functional Reps`, we would like to create an organization called *OSSN*. This is the group of people participating in Mozilla's Open Source Student Network (opensource.mozilla.community).

The identities should be sourced from this file:
https://github.com/mozilla/participation-metrics-identities/blob/master/OSSN-31-May-2018.csv

/cc @bacharakis 

Best regards,
   Henrik

**Comment by sanacl** [comment]
The github accounts have inserted, however it did not produced any matches so we'll have to manually look for the emails and names of those people. Reminder: we are not using the "name" as valid token to unify accounts as it can create wrong results in such a big database.

I'll review the accounts again after #179 as more information gathered from the data sources could help us here.

Waiting until #179 is done.

**Comment by sanacl** [comment]
@bacharakis @hmitsch data is ready, see activity for the OSSN members during last 90 days: https://analytics.mozilla.community/goto/cf0a462a62cad2ca57e70ef80ae9cc8e
