### ISSUE TITLE
As an Activate program manager, I want to have a weekly/monthly number of unique mobilizers (event organisers) who are hosting MozActivate events so that I can see it on the Metrics Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#18]
Data source = Reps portal

**Comment by hmitsch** [comment]
Requires initiatives in the Community Analytics portal: https://github.com/mozilla/participation-metrics-org/issues/9

**Comment by sanacl** [comment]
I'll confirm whether this is feasible asap

**Comment by brianking** [comment]
Poking around at https://analytics.mozilla.community I seem to be able to get this data.

I go to 'Reps2 Activities' and apply the following filters:

- Initiative: "MozActivate"
- activity: "Organized an Event"
- A time filter using the drop down on the top right of the site

So if I filter from 1-31 October I get 40 hosts.

Question: Can I have this data presented on a separate 'MozActivate' dashboard on the site?

**Comment by couci** [comment]
Separate dashboard is not needed for now since we are moving to a strategy of most reps activities will be activate.
