### ISSUE TITLE
Missing Reps Data (Events & Activities)

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/participation-metrics-org#183]
It seems that we are missing some Reps data.

Events
---

According to the "Last events" table, there were no events between Sep 9th and 14th. However, on the Reps Portal, you can see that there definitely were events:

<img width="558" alt="screen shot 2018-09-19 at 23 56 38" src="https://user-images.githubusercontent.com/330324/45809242-fdf4e900-bcc7-11e8-9e5a-21d5c52d982b.png">

<img width="540" alt="screen shot 2018-09-19 at 23 56 43" src="https://user-images.githubusercontent.com/330324/45809291-16650380-bcc8-11e8-8383-60913a5a879c.png">

<img width="1033" alt="screen shot 2018-09-20 at 11 26 47" src="https://user-images.githubusercontent.com/330324/45809301-1d8c1180-bcc8-11e8-929b-32c845bd14aa.png">

Activities
-----

The same goes for Activity Reports. You can take my reports as an example. When I choose "Last 30 days" the most recent recent report from me in the "Last activities" table is from August 28th. I've had reports since then:

<img width="541" alt="screen shot 2018-09-19 at 23 55 03" src="https://user-images.githubusercontent.com/330324/45809363-43b1b180-bcc8-11e8-8cfe-3fb2b881176b.png">

<img width="1279" alt="screen shot 2018-09-20 at 11 25 02" src="https://user-images.githubusercontent.com/330324/45809405-5b893580-bcc8-11e8-86c4-933ea17ba35d.png">

<img width="510" alt="screen shot 2018-09-20 at 11 23 55" src="https://user-images.githubusercontent.com/330324/45809412-5f1cbc80-bcc8-11e8-96df-18efd74b22bb.png">

For both cases it doesn't seem that the imports stopped as there are very recent entries, but rather that there are entries missing inbetween (gaps). Could you have a look at this?

Thanks!

**Comment by mafesan** [comment]
Hi @MichaelKohler,

Thank you for your feedback. Our team reviewed this data last week and indeed there was a gap with data from Sep 10th to Sep 14th. 

We have generated a new raw index and the missing data is now available.

![mozilla-reps](https://user-images.githubusercontent.com/9032790/46284941-e9dba200-c579-11e8-95da-6c45abb2a076.png)

Sorry for the inconveniences!

**Comment by MichaelKohler** [comment]
Thanks for your work! I've had a look again and discovered some other dates where the import did not work. This seems to be an ongoing issue.

# Events

<img width="646" alt="screen shot 2018-10-01 at 14 17 28" src="https://user-images.githubusercontent.com/330324/46288463-0ed61200-c586-11e8-8b2d-1149841ba37c.png">

There are some gaps here, I've looked at two of them:

Sep 27th does not have any events in Kibana, there were 4 events on the Portal:

<img width="1028" alt="screen shot 2018-10-01 at 14 17 01" src="https://user-images.githubusercontent.com/330324/46288478-1bf30100-c586-11e8-8b77-86e5b84cd779.png">

Sep 25th does not have any events in Kibana, there were 2 events on the Portal:

<img width="1006" alt="screen shot 2018-10-01 at 14 18 11" src="https://user-images.githubusercontent.com/330324/46288496-3036fe00-c586-11e8-9229-eef6df1cd97f.png">

Please note that the gap on Sep 19th and on Sep 10th are correct!

# Activities

Did you have a chance to look at the Activities as well? There are many gaps here and I don't see - on first sight - any improvement there. Just to make sure, what is the field from the API that you take as date? Not that it matters, as most gaps of those should not exist no matter which field it is.

<img width="641" alt="screen shot 2018-10-01 at 14 32 48" src="https://user-images.githubusercontent.com/330324/46288714-f286a500-c586-11e8-8d8b-0281138c94b2.png">

For example there is a big gap between Sep 23rd and Sep 28th with absolutely no reports. Given the fact there were events, there are at least those automatically generated reports available on the Portal. The same goes for the gap between Sep 16th and Sep 21st and possibly others before that.

<img width="1015" alt="screen shot 2018-10-01 at 14 36 16" src="https://user-images.githubusercontent.com/330324/46288941-cae40c80-c587-11e8-8c6c-7eea9795d25a.png">


<img width="1016" alt="screen shot 2018-10-01 at 14 37 34" src="https://user-images.githubusercontent.com/330324/46288865-8e181580-c587-11e8-8f18-39568e71a83e.png">


It's possible that *some* days didn't have any report, but definitely not that many, as said above, every event generates an automatic report as well. So if there was no event on one day and nobody filed a manual report, then it could be empty. But not otherwise.

# Conclusion

Once these issues are fixed, I can also verify the total amount per day, as I've not looked into that yet, but I assume for now that if something is imported, the total is correct.

You can check out https://reps.mozilla.org/reports as graphical interface to the API for the reports and https://reps.mozilla.org/events/#/period/past/ for the events.

Thanks so much for having another look into this!
Michael

**Comment by Mte90** [comment]
I am joining only because I am curious about why this is happening :-)

**Comment by mafesan** [comment]
Thank you @MichaelKohler for your detailed comment. We are having a deeper look into this issue, we will get back to you as soon as we can provide more information about it. Please stay tuned!

Best, Miguel-Angel

**Comment by mafesan** [comment]
Hi,

We are currently working to upgrade your dashboard to the newest version of the platform, so we are waiting until the upgrade is ready to test this issue again with our latest release. Sorry for the inconveniences!

Best, Miguel-Angel

**Comment by sanacl** [comment]
Hey @mafesan , the upgrade is done so we are not using software from the past. Let's push this task as we are now able to apply any fix needed in our software.

**Comment by mafesan** [comment]
Thank you for the heads-up @sanacl! Our team is reviewing this issue again after the upgrade and we will post a comment as soon as we get more information. Please stay tuned! (cc @MichaelKohler, @Mte90).

Best, Miguel-Angel

**Comment by mafesan** [comment]
We were working on this issue but our Dev team could not reproduce this bug :bug:, so we have taken the following actions:
* The indexes have been re-generated and we confirm the data is updated. 
* We are performing daily checks comparing the number of elements in the original source against the number of elements in the indexes, to see where these discrepancies are produced.
* We will share this results periodically, updating this ticket with the current status of this issue.

Best, Miguel-Angel

**Comment by hmitsch** [comment]
Instead of pursuing the _incremental data update_ approach. The Reps data is now **fully refreshed** every day.
