### ISSUE TITLE
Introducing our brand-new dashboard menu

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#185]
Hi there!

We have some news about your dashboard at https://analytics.mozilla.community! We are improving the user experience by including a brand-new navigation menu to navigate through the different panels on your dashboard. You will find this new menu as the top bar, instead of the left navigation bar that was previously used.

# What's new?

* You will keep seeing the navigation menu even if you are logged in on the editable part of your dashboard, which means this new menu does not interfere with the dashboard applications (Discover, Visualization, etc.) menu anymore.
* We are using the panels description field to show it on the left when you "hover" your mouse over the elements inside the menu without having to click on them. We will be updating the panels short descriptions during upcoming releases.

# When will this menu be available?

This new menu will make its appearance with our latest release of the platform, which will be deployed during this week.

Feel free to post a comment with any question you may have!

Best, the Bitergia team

![menu](https://user-images.githubusercontent.com/326719/49011256-212f8f00-f176-11e8-8668-2921dfd05303.gif)

**Comment by sanacl** [comment]
Hello folks,
the dashboard at https://analytics.mozilla.community will be unavailable on Tuesday from 10AM to 10:15AM CET to apply the new menu.

CC @hmitsch

**Comment by sanacl** [comment]
Hello folks,
the dashboard at https://analytics.mozilla.community will be unavailable on Thursday from 10AM to 11AM CET to apply the new menu.

CC @hmitsch

**Comment by hmitsch** [comment]
The new menu is live! Thanks a lot.

**Comment by mafesan** [comment]
Hi folks!

I'm just adding some screenshots here to let you know about the newest panels we have added with the latest update:

* GitHub Issues Efficiency panel
![github-issues-efficiency](https://user-images.githubusercontent.com/9032790/50399760-220e0d80-0782-11e9-8732-5aa5408c5cfe.png)

* GitHub Pull Requests Efficiency panel
![github-pr-efficiency](https://user-images.githubusercontent.com/9032790/50399767-305c2980-0782-11e9-9b09-84f5d45962b5.png)

* Affiliations panel, with direct links to Hatstall profiles
![affiliations](https://user-images.githubusercontent.com/9032790/50399815-77e2b580-0782-11e9-8074-d63155cb245a.png)

Please, let us know if you have any comment or question.

Merry Christmas! :santa:

**Comment by sanacl** [comment]
Thanks for the feedback @hmitsch . We've already noticed the timeouts with the affiliation panel and a fix is on its way. 

The issue is not with the Hatstall database but with a too heavy query sent to the ES server. We are thinking how to improve the performance of the panel. The worst case scenario is a limitation in the query to avoid loading all the possible results (contributor names, affiliation, etc) in on of the tables which BTW is not quite useful in my opinion. 

Best!

**Comment by sanacl** [comment]
Our latest release fixed the issue with the "Community" -> "Affiliations" panel, please check.

Moving the ticket to done.

**Comment by sanacl** [comment]
@hmitsch I'm closing this ticket as this is already working, if you find a bug related to this panel please open a new ticket.
