### ISSUE TITLE
Reduce number of monitored data sources

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#188]
Since March 1st the dashboard at https://analytics.mozilla.community will follow/monitor less data sources.

The data sources will be:
* Git source code management
* Github Issues and Pull Requests
* Bugzilla issue tracking system
* Discourse forums
* StackOverflow
* Mozilla Reps
* Meetup

**Comment by sanacl** [comment]
Hi @hmitsch , this is planned for this Thursday but we could finish it sooner if you want.

Best.

**Comment by hmitsch** [comment]
Please finish at your earliest convenience. We don't need to wait for 01 MAR, if this is what you were referring to.

**Comment by sanacl** [comment]
This is a work in progress. It will be finished on Monday morning (CET timezone)

**Comment by sanacl** [comment]
@hmitsch before closing this task I think it is a good idea to review the spreadsheet we use to feed the GrimoireLab toolset. The only change we need is to prune it by removing the decommissioned data sources. Do u want us to do that @hmitsch ?

**Comment by hmitsch** [comment]
@sanacl, yes please prune the sheet. Excellent catch!

**Comment by sanacl** [comment]
This is done.

* projects.json file used by the platform was updated: https://github.com/Bitergia/projects-mozilla/commit/d113d7a7123559d1f9788c72a9968a0fda90bfde
* spreadsheet was updated: https://docs.google.com/spreadsheets/d/1xFrt9JZkZ6m8peasYaRfPO5kC1JDo-vDJJuYfMwcGqM/edit#gid=0
