### ISSUE TITLE
Load identities data to SOTRAR instance

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#192]
The aim of this ticket is to load identities+affiliations data provided by @hmitsch.

**Comment by sanacl** [comment]
Data was converted to Sortinghat format and it is being loaded since Wednesday afternoon. When this is done the software will refresh the identities+affiliations data for all the updated records.

**Comment by sanacl** [comment]
Data is ready in the SQL database, the ES database will be synced during the next hours.

**Comment by sanacl** [comment]
Data is loaded in SH database. When data was loaded we checked the new changes to make sure we don't have errors. 

We can close this ticket, new affiliation data will be ready via enriched indexes when ticket #196 is done.

**Comment by havardl** [comment]
Can we add the SOTRAR label to this, and any other issues relevant for the project?

**Comment by sanacl** [comment]
@havardl done!
