### ISSUE TITLE
Access to SortingHat database

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#194]
In order to query data our A&T folks will need access to the SoringHat database. We have several options here, one is to give them access to the one used by the report, another one is to create a copy of it.

I'm ok with both of them so we will need @hmitsch to help us with this decision.

**Comment by hmitsch** [comment]
Hi @sanacl, I suggest giving A&T access to the SortingHat db on sotrar.mozilla.community.

Let's share credentials in our secure Keybase group.

-Henrik

**Comment by havardl** [comment]
We have access now, so this is resolved.

**Comment by sanacl** [comment]
Thanks for the confirmation @havardl. Really appreciated :D

I'm moving this to Done, if you need anything else please reopen the ticket.
