### ISSUE TITLE
Remove the repository gecko (not the gecko-dev) from the existing analysis at SOTRAR

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#198]
The description below was initially written by @dicortazar.

The goal of this task is to remove gecko from the existing analysis in the SOTRAR database.

According to our meeting yesterday, there are two repositories of interest related to Gecko: gecko (with around 400K commits) and gecko-dev (with around 600K commits). The goal of this task is to remove duplicates and to be sure that we have the most complete repository.

For this, the decision during yesterday meeting was to remove gecko from the list of repositories and the dataset and leave gecko-dev as the repository that is part of this analysis.

Warning!: Please notice that we only want to remove one repository, gecko, and we want to leave gecko-dev!

**Comment by sanacl** [comment]
Can anyone confirm this is the repo we want to remove?
`https://github.com/mozilla/gecko.git`

CC @hmitsch @dicortazar 

Thank u.

**Comment by hmitsch** [comment]
Yes, I *confirm* that this is the repo we want to remove. Thanks a lot! Can you also update the _Project Grouping_ spreadsheet?

-Henrik

**Comment by sanacl** [comment]
> Yes, I **confirm** that this is the repo we want to remove. Thanks a lot! Can you also update the _Project Grouping_ spreadsheet?
> 
> -Henrik

Sure. I'll deal with it :+1:

**Comment by canasdiaz** [comment]
This ticket will be 100% finished when  #204 is done. The indexes where this must be updated are git AOC and git ONION. It is done for the rest of indexes.

**Comment by canasdiaz** [comment]
#204 is done and indexes are updated. Ready to be closed @hmitsch
