### ISSUE TITLE
Dashboard for MoFo Mozilla Clubs

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/participation-metrics-org#2]
Source - http://mozilla.github.io/clubs-events/

**Comment by hmitsch** [comment]
@sanacl: Can you please assign this issue to yourself?

**Comment by jsmanrique** [comment]
Does it provides an API to query data somehow?

**Comment by hmitsch** [comment]
Hi @comzeradd,

can you answer @jsmanrique's question?

Best regards,
   Henrik

**Comment by comzeradd** [comment]
This website is fetching data out of a specific google spreadsheet. Through this [json endpoint](https://spreadsheets.google.com/feeds/cells/1QHl2bjBhMslyFzR5XXPzMLdzzx7oeSKTbgR5PM8qp64/ohaibtm/public/values?alt=json).

@jsmanrique does this suffice for using it on kibana?

**Comment by jsmanrique** [comment]
It might work. Let me check with the team

**Comment by jsmanrique** [comment]
Since MDN API doesn't provide useful data, we might use resources to work on supporting this data source instead of MDN. What do you think?

**Comment by hmitsch** [comment]
@jsmanrique, which ticket describes the issues you have with MDN?
I am not sure I want to sacrifice MDN for Club Events. I'd rather go for a "both yes" implementation.

If you provide me with more details on the current state of affairs with MDN integration, I will be able to consult with George (and others) and get back to you.

-Henrik

**Comment by jsmanrique** [comment]
I will ask @acs about it, because he was the one working on it

**Comment by hmitsch** [comment]
Following a conversation with Bitergia, we decide to switch MDN for Club Events.

**Comment by acs** [comment]
@hmitsch working now in the backend implementation. As soon as we have a first version to be checked, we will report about it ... probably during this week it must be working.

**Comment by acs** [comment]
@hmitsch coudl you check a draft panel we have created for this Mozilla Club Events data source?

https://mozilla.biterg.io/app/kibana#/dashboard/MozillaClubDebug

With your feedback we can create the final version.

**Comment by hmitsch** [comment]
Hi @LucyeoH,

the Bitergia people have built a first version of the Mozilla Clubs panel. This is what it looks like:

<img width="1115" alt="screenshot 2016-09-30 00 28 23" src="https://cloud.githubusercontent.com/assets/869692/18974686/ee4dee8a-86a4-11e6-97e1-5911314ab631.png">

Is this what you are looking for? What is it missing? What else would you like to see?

Best regards,
   Henrik

**Comment by LucyeoH** [comment]
@hmitsch this looks awesome! It DOES raise some more general thoughts for me about being careful not to aggregate "self report data" like this with not self-reported data which could totally inflate our numbers. Even those first few reports suggest to me people are massively exaggerating :P and we know from TBTW that people are usually adding at least 1 zero to any number they're asked to self report. Which is totally fine, unless this ends up going into a more broad equation with non-self reported numbers and ending up suggesting a broad kind of activity we don't actually have.

**Comment by LucyeoH** [comment]
@hmitsch 
I’d  love more info about where this data came from (is it from the clubs page? reps portal? made-up?)

There's lots more data I would love to see but not sure how much you can give us i.e.: 
    * Club Enrollement (taken from report forms) how many ppl are in their club
    * RC - who is their RC
    * Active for how long - how long have they been active for (reporting on a monthly basis) 
    * A column that shows Clubs who have missed (1,2,3) reports
    * RC tracking - Which RC's are active (have completed training, submitted a year plan, and are reporting regularly) 

We can talk more through this on Wednesday!

**Comment by acs** [comment]
@LucyeoH the data is extracted from:

https://github.com/acs/perceval/blob/mozilla-club/perceval/backends/mozillaclub.py#L42

this spreadsheet. Not sure if in this spreadsheet all the data you are looking for is included.

**Comment by LucyeoH** [comment]
For Henrik - Julia Vallera is the person for whom this data is immediately useful.

**Comment by hmitsch** [comment]
Mail sent to Julia. Waiting for response.

**Comment by hmitsch** [comment]
@bacharakis do you have the JSON endpoint for the Participation Mozilla Club event reports, i.e. the form filled via http://mozilla.github.io/clubs-events/

We want to add the results to Bitergia Community Analytics.

**Comment by hmitsch** [comment]
Dashboard was presented to Julia. She loves it.
Additionally, the data is now updated regularly.

Closing issue. Thank you very much!
