### ISSUE TITLE
Add repo https://github.com/mrdoob/three.js/

### ISSUE THREAD

**Issue by canasdiaz** [mozilla/participation-metrics-org#207]
Add repo named https://github.com/mrdoob/three.js/ under the project named "WebVR - three.js"

The repo contains aprox 30K commits, 10K issues and 10K PRs. So this may impact the work done by @havardl

**Comment by canasdiaz** [comment]
This is done. Commits, Issues and PRs added to the standard indexes.

I will close the ticket when @havardl @hmitsch give me the ACK to make sure they are aware of this.

**Comment by hmitsch** [comment]
Thanks a lot!

**Comment by havardl** [comment]
@sanacl - which index is three.js added to?

**Comment by canasdiaz** [comment]
Here you are @havardl :
* git: https://sotrar.mozilla.community/goto/11e20a410a0679181e9c4d442fa794a5
* git_areas_of_code: https://sotrar.mozilla.community/goto/9a6e97ab350d71ee525dcb53cf292de5
* github_issues: https://sotrar.mozilla.community/goto/47399ec6c1fb6d3740a4e3b92db8ad2f
