### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of unique social shares to the MozActivate Campaign in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#25]
Current information sources (system and data fields):
Currently being retrieved manually on twitter.com using the #MozActivate campaign. Would be nice to have Instagram posts and public FB posts, and anything else that might make sense.

**Comment by jsmanrique** [comment]
Currently Twitter is not part of the data sources covered by Mozilla - Bitergia agreement.
FB and Instagram are not part of [GrimoireLab](http://grimoirelab.github.io) platform. It would require development effort.

**Comment by hmitsch** [comment]
https://github.com/mozilla/participation-metrics-org/issues/51

**Comment by brianking** [comment]
I would say Twitter would be sufficient.

**Comment by mermi** [comment]
If you would extract Data from Twitter or any other Social Media Account is better to use Sentimental Analytics tools with Bitergia you can't extract Data from Fb, Instagram or either Twitter. 
So I think the best idea is to try [Heartbeat Analyses](https://github.com/sarahsharp/foss-heartbeat) tool I think you can get what you want with it, it's my personal suggestion.

**Comment by couci** [comment]
we have this now on our twitter analytics
