### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of people hosting Rust events as part of the MozActivate Campaign in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#26]
Current information sources (system and data fields):
Reps Portal -- MozActivate initiative events that mention Rust (in title or description)

**Comment by brianking** [comment]
What would be nice to have here is:

- the number of Rust events in a time period
- the number of unique hosts of Rust events in a time period

One way the dashboard is surfacing this up now in 'Reps2 Activities' is via Reps reports. However, this is flawed for 2 reasons. 

- Reps don't always file reports
- Attendees can also file reports, meaning it won't only be hosts

So as I mentioned when filing this, I think we need to do is:

- filter by "MozActivate"
- search title and description of events for "Rust"
- see how many of these have unique hosts

Would be great just to have an overall total of Rust events over time.

@sanacl do you think this is feasible?

**Comment by couci** [comment]
this was fixed with the last update with functional areas, closing
