### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of people attending Rust events as part of the MozActivate Campaign in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#27]
Current information sources (system and data fields):
Number of attendees (NOT people who sign up) of MozActivate Rust events on the Reps portal. Many Reps don’t fill in the actual event after, so in this case we should use the estimated.

**Comment by couci** [comment]
This can be resolved based on the last addition of functional areas in the portal, closing
