### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of people hosting WebCompat events as part of the MozActivate Campaign in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#30]
Current information sources (system and data fields):
Reps Portal -- MozActivate initiative events that mention ‘WebCompat’ or ‘Web Compat’ or ‘Web Compatibility’ (in title or description)

**Comment by couci** [comment]
this has been resolved based on the last addition of functional areas in the analytics site
