### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of installs of the Test Pilot Add-on in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#34]

**Comment by brianking** [comment]
Current information sources (system and data fields):
The Test Pilot team set up a special tracking url: http://testpilot.firefox.com/experiments?utm_source=activity.mozilla.community&utm_medium=referral&utm_campaign=moz-community-2016
Being sent a Google Analytics report to my email.

**Comment by couci** [comment]
not active any more, closing
