### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of times people social share the Test Pilot activity in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#35]
Current information sources (system and data fields):
The activity is here: https://activate.mozilla.community/experiments/test-pilot/
We have not been segmenting tweets to #MozActivate yet.
I’m guessing the best way to get it is to check for tweets that have the #MozActivate tag and also mention Test Pilot in the text.

**Comment by couci** [comment]
not active any more, closing
