### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of people hosting ‘e10s and Featured Addons’ events as part of the MozActivate Campaign in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#37]
Possible information sources (system and data fields):
Reps Portal -- MozActivate initiative events that mention ‘e10s’ or ‘Add-ons’ (in title or description)

**Comment by couci** [comment]
Not an active activity any more, closing
