### ISSUE TITLE
As an Activate PM I want to have a view of the number of add-ons that get testing coverage during the ‘e10s and Featured Addons’ activity which runs until November 4 as part of the MozActivate Campaign in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#39]
Possible information sources (system and data fields):
@wagnerand will probably be able to pull this from the back-end of https://featured-addons-test.herokuapp.com/

**Comment by jsmanrique** [comment]
`Featured Add-ons Compatibility Test` as a data source is not covered by Bitergia - Mozilla agreement, and would require development to set up a backend

**Comment by hmitsch** [comment]
Hi @brianking,

please reach out to me after your PTO to discuss the information architecture of this story.

Thanks in advance and best regards,
   Henrik

**Comment by couci** [comment]
activity no longer active
