### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of individual add-on tests during the ‘e10s and Featured Addons’ activity as part of the MozActivate Campaign in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#40]
Possible information sources (system and data fields):
@wagnerand will probably be able to pull this from the back-end of https://featured-addons-test.herokuapp.com/

**Comment by jsmanrique** [comment]
`Featured Add-ons Compatibility Test` as a data source is not covered by Bitergia - Mozilla agreement, and would require development to set up a backend

**Comment by couci** [comment]
e10s and Featured addons is not an active activity thus closing this one
