### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of people hosting ‘WebVR Camp’ events as part of the MozActivate Campaign in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#41]
Possible information sources (system and data fields):
Reps Portal -- MozActivate initiative events that mention ‘WebVR’ or ‘A-Frame’ or ‘AFrame’ (in title or description)

**Comment by couci** [comment]
This will be resolved with adding categories on the community analytics.
