### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of people attending ‘WebVR Camp’ events as part of the MozActivate Campaign in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#43]
Possible information sources (system and data fields):
Number of attendees (NOT people who sign up) of MozActivate ‘WebVR Camp’ events on the Reps portal. Many Reps don’t fill in the actual event after, so in this case we should use the estimated.

**Comment by couci** [comment]
This will be resolved once we have the categories on community analytics
