### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of new signups to the A-Frame Slack Channel as part of the MozActivate Campaign in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#44]
Possible information sources (system and data fields):
https://aframevr-slack.herokuapp.com/
Slack API?
Will be difficult to differentiate campaign signups from regular ones, maybe we don’t need to.

**Comment by jsmanrique** [comment]
Currently Slack is not part of the data sources covered by Mozilla - Bitergia agreement and it would require development to add it to GrimoireLab platform. It is planned to be added by the end of the year or early 2017.

I am worried that Mozilla might have the same security/privacy concerns that with Telegram and IRC.

**Comment by hmitsch** [comment]
@brianking please clarify privacy question.

**Comment by couci** [comment]
issue same with #45 so I am closing this one
