### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of blog posts about the MozActivate Campaign ‘WebVR Camp’ activity or inspired by it in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#46]
Possible information sources (system and data fields):
@gurumukhi and @ngokevin might have an idea

**Comment by couci** [comment]
WebVR Camp activity will change so this is no longer needed. If we decided that blogposts is a meaningful metric I will reopen this one.
