### ISSUE TITLE
As an Activate PM I want to have a weekly view of the number of times people social share the WebVR activity in order to visualize them on the Main Activate Campaign Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#47]
Possible information sources (system and data fields):
People sharing on social networks (especially tweets) #MozActivate AND #WebVRCamp OR @aframevr OR @mozillavr

**Comment by jsmanrique** [comment]
Currently Twitter is not part of the data sources covered by Mozilla - Bitergia agreement.

**Comment by hmitsch** [comment]
Pursuing twitter integration in https://github.com/mozilla/participation-metrics-org/issues/50

**Comment by hmitsch** [comment]
test comment

**Comment by couci** [comment]
#MozActivate has already been made. @hmitsch I will gather twitter hashtags that we are interested noow to track and share with you. Right now we don't need this anymore
