### ISSUE TITLE
VM is down

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#49]
VM used to gather and update dashboards is down. IP address 54.67.78.223

**Comment by hmitsch** [comment]
@flamingspaz can you please help?

**Comment by flamingspaz** [comment]
I kicked it and it's back up now.

**Comment by acs** [comment]
@flamingspaz it is down again. Could you check it? Thanks a lot!

**Comment by flamingspaz** [comment]
Done again, I would recommend limiting the load until we decide on the new resources.

**Comment by acs** [comment]
@flamingspaz thanks. Yes, we need to retrieve and enrich data less frequently to low the load. But if people start to use the dashboard we will have problems.
