### ISSUE TITLE
(Deployment) Enhance identfication of Mozilla employees using curated email list

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-metrics-org#5]
See email exchange with Mike Hoye.

**Comment by geroter** [comment]
Let me know where this can fit as a feature @sanacl

**Comment by hmitsch** [comment]
@sanacl, please update the issue!

**Comment by jsmanrique** [comment]
We are waiting for the file from Mike ;-)

**Comment by hmitsch** [comment]
Info from @mhoye from earlier this week:
> I'll be transferring that curated list to Bitergia this week after clearing the PII situation with our security and compliance team.

Waiting for next week to follow up with @jsmanrique.

**Comment by hmitsch** [comment]
Just sent a friendly reminder to @mhoye.

**Comment by hmitsch** [comment]
List was imported recently. Closing issue.

**Comment by sanacl** [comment]
Hi again @hmitsch. I've reviewed the log of the deployment and it is not clear that we've imported this data in the identities database. I'm claiming it and solve it by next week's call.

**Comment by sanacl** [comment]
Data is already loaded in the Sorting Hat (identities + affiliations) database This tasks depends on finishing to produce the index named: git_mozilla_160801_enriched_161201

**Comment by sanacl** [comment]
New index published.

Can we close this ticket?
