### ISSUE TITLE
(Deployment) Cross-index searches

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#55]

**Comment by hmitsch** [comment]
Create an example dashboard showing how to search across various data sources (indexes).

**Example:** Search for "Henrik's contributions" (hmitsch on Wiki, Reps, Mailing List, etc)

**Comment by hmitsch** [comment]
Another example:

**Contributor Panel**
The panel shows the number of contributors from **all** data sources.
* Git
* Bugzilla
* Reps
* Kitsune
* Wiki
* ...

**Comment by sanacl** [comment]
See https://github.com/mozilla/participation-metrics-org/issues/65#issuecomment-264162306

**Comment by sanacl** [comment]
Can we close this ticket?

**Comment by hmitsch** [comment]
Successful acceptance test done using the **Overview dashboard** (see https://analytics.mozilla.community:443/goto/720fbb09d1cfed6b28863e245555c770).
