### ISSUE TITLE
Rust community metrics

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#58]

**Comment by hmitsch** [comment]
Backlogged from mailbox.

**Comment by hmitsch** [comment]
# Data Sources
The following data sources are desired to be tracked.
* Rust Discourse: https://users.rust-lang.org/
* StackOverflow: https://stackoverflow.com/questions/tagged/rust
* IRC: several #rust* channels in irc.mozilla.org
* Several Meetup based and custom based meeting sites: https://www.rust-lang.org/en-US/user-groups.html
* Rust's GitHub repos
* Track crates.io
* Track internals.rust-lang.org

# Tracking Metrics
The kinds of things that seem to be of interest are:
* Rate of growth in terms of users, contributions
* Percent of mozilla vs non-mozilla contributors
* Community involvement, rate of new contributors, burnout (contributors that leave), retaining contributors (contributors that stay)
* For crates.io: rate of growth in terms of # of projects. 
    * In the future, we'd like to track quality of project but we don't have a way to measure that, yet.
    * Crates.io also often ties projects back to github, so we can identify more unique users that way.

# Visibility
Who do these metrics need to be available to?
* Non-mozillians: most members of the Rust community team are employed elsewhere
    * Implementation detail: Check if we need set up a separate dashboard for the Rust Community

**Comment by hmitsch** [comment]
# Scope Desirement
Create a "Rust Community" **tab**

# Data Source Assessment
* **Meetup:** will be ready until the end of year
* **crates.io:** We need an API specification, it will take approximately until beginning of Q2/2017 to develop the Bitergia Perceval backend
* **internals.rust-lang.org:** We need an API specification, it will take approximately until beginning of Q2/2017 to develop the Bitergia Perceval backend

# Metrics Assessment
* user and contribution growth rate: OK
* mozilla vs non-mozilla contributors: OK
* Community involvement, rate of new contributors, burnout (contributors that leave), retaining contributors (contributors that stay): This data can probably be derived from the Demographics tab

# Visibility Assessment
* Further checks by Bitergia required

**Comment by jonathandturner** [comment]
Adding myself to the thread

**Comment by jsmanrique** [comment]
After asking @sanacl, we could have/provide:
* Project "rust-lang" tagged in current analytics.mozilla.community (as we already do for git and github). So you would be able to filter by "rust-lang" project in git and github tabs, and we could add meetup tab including "rust-lang" project and maybe others from Mozilla
* Set up a separate dashboard with just "rust community" tabs

In any case, you would have:
* github activity, that would include rate of growth in terms of contributions and percent of mozilla vs non-mozilla contributors
* meetup activity, that would include rate of growth in terms of meetings, attendees registered
* git demography, that would show rate of new contributors, burnout (contributors that leave), retaining contributors (contributors that stay)

**Comment by sanacl** [comment]
@hmitsch with the current VM and database we can deal with more projects like rust. What we would need is a new ES. I've been working on an estimation for it:
* **64GB RAM** for ES is needed
* **500 GB for HD** the current version would use around 50 GB HD but, the next version based on events will impact on the size of the information. Our first tests say we will have x20 space needs. I mean, if we can scale it up easily let's start with 50 and increase it later.

**Comment by hmitsch** [comment]
Updated https://tree.taiga.io/project/pierros-mozilla-particiaption-systems/us/185?kanban-status=904519 according to @sanacl's spec.

**Comment by sanacl** [comment]
Hi guys, I want to polish up our internal planning and would love to know what is the ETA for having the Elastic Search server for Rust. Thank you!

**Comment by flamingspaz** [comment]
Hey folks, This was done a while ago and the instance is up at search-bitergia-rust-metrics-es-zz47dbqnlapavj6rd23tpdp62m.us-west-1.es.amazonaws.com

**Comment by jonathandturner** [comment]
Thanks for the reminder.  I need to run this through the Rust core team before we start publicizing it.  If I recall, there were a few changes we might want before it's "live".

**Comment by hmitsch** [comment]
Rust dashboard is live. Closing issue.
