### ISSUE TITLE
What is GitHub project "Main"?

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#60]

**Comment by jsmanrique** [comment]
I think @sanacl can explain it better, but I will try.

"Main" project is the one where repositories not assigned to any project in the configuration file are assigned. 

In your case, there has been an issue during latest deployment and the file was wrong. Some repositories ended tagged as part of "Main" project.

Indexes are being rebuilt, and during following hours fresh data will be uploaded, and tomorrow "Main" project should have gone.

**Comment by jsmanrique** [comment]
Issue solved. Would you mind check it @hmitsch?

**Comment by hmitsch** [comment]
This was a bug by Bitergia which was fixed.
