### ISSUE TITLE
ReMo Categories on the ReMo Dashboard

### ISSUE THREAD

**Issue by couci** [mozilla/participation-metrics-org#66]
Right now on the RepsV2 dashboard we are able to filter based on activities and initiatives however we can not filter based on categories (for example rust, l10n, addons etc)

Is that a feature we can have?

**Comment by acs** [comment]
@couci yes, you can have it. I have reviewed the data in the current indexes and it is not included in the index used in Kibana, but the information is included in the raw index collected from ReMo v2 API. So we need to propagate the data and include the filter in the dashboard.

**Comment by acs** [comment]
@couci we can add categories for the events, but not for the activities because this information is not included in the data offered by the API. For example:

https://reps.mozilla.org/api/remo/v1/activities/40822/

**Comment by couci** [comment]
That would be a good first step. Since this is going to be only for events, are we going to include both conducting an event and participated on an event activities or just conducted events?

**Comment by hmitsch** [comment]
"activity": "Attended an Event",
    "initiative": null,
    "functional_areas": [
        {
            "name": "Connected Devices"
        }

**Comment by hmitsch** [comment]
# Example

- Reps Event Page: https://reps.mozilla.org/e/mozactivate-tour-training-1/
    > Category: Technical Evangelism
- Bitergia Event: https://analytics.mozilla.community/edit/app/kibana#/doc/remo2-events/remo2-events-dev_161122_enrich_161122/items?id=fbcb20c391c5f0d772b240ddadebf364a897ef3c&_a=(filters:!(),query:(query_string:(analyze_wildcard:!t,query:'*')),vis:(aggs:!((params:(field:initiative,orderBy:'2',size:20),schema:segment,type:terms),(id:'2',schema:metric,type:count)),type:histogram))&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1y,mode:quick,to:now))
    > No "Technical Evangelism" anywhere

**Comment by hmitsch** [comment]
Reps API Event: https://reps.mozilla.org/api/remo/v1/events/6208/

>   "external_link": "",
    "initiative": "MozActivate",
    "categories": [
        {
            "name": "Technical Evangelism"
        }

**Conclusion:**
We need the `categories name` in Bitergia Community Analytics.

**Comment by acs** [comment]
@hmitsch working on adding this field, categories name, to Bitergia Community Analytics. We will add also a widget to filter events using it. Probably before next Monday meeting it will be done.

**Comment by couci** [comment]
Hello,
I was wondering when will we have this since we need the data in order to send targeted messages to some of our Reps

**Comment by jgbarah** [comment]
We already have the changes needed to the software: a new version of Gelk producing the needed indexes, and some new panels. AFAIK, everything is scheduled to be deployed during this week. @acs if you have more precise info, please let us know.

**Comment by hmitsch** [comment]
@acs any updates on this? Did the deployment happen?

**Comment by acs** [comment]
@hmitsch I think the current deployment has already this fix/feature. @sanacl could confirm it.

**Comment by sanacl** [comment]
The new set of indexes still needs to be move to production. Tomorrow we'll switch the old ones and you'll have the latest data we gather with our latest software.

**Comment by sanacl** [comment]
Hi @hmitsch and @couci, first live versions of the panels ready. We're switching the link to these new ones during the day:

* https://analytics.mozilla.community/edit/app/kibana#/dashboard/Reps-Events
* https://analytics.mozilla.community/edit/app/kibana#/dashboard/Reps-Activities

**Comment by couci** [comment]
cool beans! thanks so much for this

**Comment by hmitsch** [comment]
This works great, thank you!

**Comment by hmitsch** [comment]
<img width="420" alt="image" src="https://cloud.githubusercontent.com/assets/869692/24096394/cd2ceabe-0d61-11e7-9969-3bb4bc7ac0d0.png">

:-(
