### ISSUE TITLE
Implement NNTP Backend in Perceval

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#68]
Work is based on new SoW.

**Comment by sanacl** [comment]
The NNTP development is being tested this week. I confirm we are on time.

**Comment by sanacl** [comment]
So far we've collected 512090 documents. Data collection still in progress.

**Comment by sanacl** [comment]
Data collection still in progress. _571771_ items collected.

**Comment by sanacl** [comment]
Data collection still in progress. _663002_ items collected

**Comment by sanacl** [comment]
Data collection finished with 826866 elements.

Data enrichment in progress with 751418 documents produced.

**Comment by sanacl** [comment]
By tomorrow data should be ready on the dashboard. The enrichment is partially done, the process still needs to add the affiliation data.

**Comment by sanacl** [comment]
Panel ready https://analytics.mozilla.community/app/kibana#/dashboard/MailingLists
