### ISSUE TITLE
Change URL of "deployment" to analytics.mozilla.community

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-metrics-org#7]
Pierros, hoping we can do this ASAP. Connected you with Luis in an email.

@sanacl

**Comment by geroter** [comment]
Changed URL to analytics.mozilla.community

**Comment by ppapadeas** [comment]
Pinged the team to deploy this

**Comment by sanacl** [comment]
Hi guys! We need to know the domain name and we'll also need the certificate to be deployed in our nginx web server in order to offer HTTPS

**Comment by ppapadeas** [comment]
@sanacl We will be issuing the SSL and terminating it on a ELB. I assume port 80 would be OK right?

**Comment by ppapadeas** [comment]
The URL will be analytics.mozilla.community and you can track the progress of the ELB setup and SSL termination here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1297145

**Comment by sanacl** [comment]
@ppapadeas ELB? I'm not familiar with that term ..

**Comment by johngian** [comment]
For more info about AWS ELB [1] please take a look here.

At the moment we are terminating SSL in a higher level of the stack and redirecting the traffic to port 443 of the bitergia VM. Is that OK?

Looks like it's working for me (it proompts for user/pass):
https://analytics.mozilla.community/

[1] https://aws.amazon.com/documentation/elastic-load-balancing/

**Comment by geroter** [comment]
Hey @sanacl looks like it's working.

Can you verify and also let us know when the data has finished migrating.

**Comment by sanacl** [comment]
@geroter We're updating data now using the new infrastructure. Stay tuned :)

**Comment by sanacl** [comment]
@geroter Hi again, we are reviewing the data of some backends like Discourse that should be working better. My colleague @acs is working on that and I'll be two weeks off. COuld you please add him to this project?

**Comment by geroter** [comment]
Done

**Comment by hmitsch** [comment]
@sanacl is this issue still open? Any work left to do here?

/cc @ppapadeas @johngian: Do you still see any open work here?

**Comment by ppapadeas** [comment]
The URL is working properly now, closing this.
