### ISSUE TITLE
Assigning people to organizations

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#70]
Bitergia will provide a final format to assign people to organizations. This is a problem they are currently solving generically for various customers.

Due Date: end of December

**Comment by sanacl** [comment]
I'm working on this during next two weeks.

**Comment by sanacl** [comment]
Hi @hmitsch , I didn't make it. It will be my top priority as soon as I come back from holidays (on January 4th)

**Comment by sanacl** [comment]
Working on it, will be delivered to you by Monday. 

I'll offer both an example and the information you guys have provided following this format (the second will be offered in a secure environment so you can check).

**Comment by sanacl** [comment]
Hi again guys. I'm working on a definition of the YAML file this week, you can check a real example at https://github.com/Bitergia/identities/blob/master/README.md

Our scenario is:
* you guys modify the identiti(es) file in GitHub
* the system notices the change and upload the information in our identities database
* the indexes are updated with the changes

Just as a reminder, the typical changes are:
* merging identities/accounts which belong to the same contributor
* updating affiliation (both adding a company or editing the starting/end date)
* changing the name shown on the dashboard

You will be the first ones to use it, so your feedback will be really appreciated.

**Comment by hmitsch** [comment]
Note from today's Bitergia call:

Mozilla is thinking of using the "organizations capability" to assign contributors to "programs" (e.g. Reps, Campus Clubs, etc).
This would require a contributor to be part of more than one organization at the same time.

Bitergia will check if this breaks the exisiting (data) architecture.

**Comment by hmitsch** [comment]
Another note:

We are aware that the current "employee list" does not contain any records on DATE. This means that a volunteer contributor who is hired (or vice versa) will always be listed as "MoCo contributor".

**Comment by hmitsch** [comment]
Let's use this private repo for the identities store:
https://github.com/mozilla/participation-metrics-identities

**Comment by sanacl** [comment]
@hmitsch it is ready

* https://analytics.mozilla.community:443/goto/5e96ff3ff4bc6dc19b64a91d2a34f943 for Michael Kohler
* https://analytics.mozilla.community:443/goto/75adbc9b8485453f7954dcc692115d3b for Henrik Mitsch
* https://analytics.mozilla.community:443/goto/e73efa99754dc33210aeb3bb1a672de0 for Daniele Scasciafratte

About the previous affiliation data, we can calculate it automatically (as we did) if you guys change your mind.

Waiting feedback :)

**Comment by sanacl** [comment]
@hmitsch data for NNTP ready https://analytics.mozilla.community/app/kibana#/dashboard/MailingLists

The unknown bucket is there with less than 1% for the last month. As soon as we upgrade to the new version (upgrading is taking place right now) we'll get rid of it.

**Comment by hmitsch** [comment]
Done.
