### ISSUE TITLE
Full event text search for MozActivate events

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-metrics-org#73]
Steps:
1. On the 'Reps Activities' dashboard, filter by MozActivate and 'Orgnaized an event'
2. Enter the strong 'compat' (without quotes) in search box and filter

Desired result:
30+ events appear, as the search covers not only event titles but also descriptions

Actual Result:
Only 7 event results appear.
It is unclear to me what is being searched here.

Searching directly on the Reps portal does better, for the same time period I used on the dashboard (8 Aug-31 Dec) I get 19 results. It seems to be only searching titles:
https://reps.mozilla.org/events/#/period/custom/start/2016-08-08/end/2016-12-31/initiative/mozactivate/search/compat/

Example of event with search string in description:
https://reps.mozilla.org/e/sfd-celebration-sns-tech-coimbatore/

**Comment by jgbarah** [comment]
I'm not sure, but I guess the search string you want in this case is "*compat*" (without the quotes). Please, check the screenshot below, which finds 25 events.

![selection_099](https://cloud.githubusercontent.com/assets/1039693/21831337/561e5c76-d7a3-11e6-9b10-6762c17ca819.png)

Is that result right, or we´re still missing some events that you expected to see?

**Comment by brianking** [comment]
Yes, this does indeed look like the right numbers @jgbarah ... thanks. I was not aware of the convention of surrounding text with asterix.

I will close for now, and re-open or file a new issue if I notice any anamolies.
