### ISSUE TITLE
Main companies chart showing wrong information

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#77]
Before upgrading the Git and Github panels to its latest stable version, we need to discuss what affiliation information we want to show.

Having a look at the companies pie chart at https://analytics.mozilla.community/app/kibana#/dashboard/Git we can see activity for "Community", "Mozilla" and a set of organizations/companies. These companies are not supposed to be there because the idea is having one (and only one) of the following views: 
- a) showing just "Community" vs "Mozilla"  (contributors who belong to companies that are not Mozilla would be included in "Community")
- b) all the companies/organizations involved ("Community" wouldn't appear) 

So, in order to improve the quality of the affiliation data I see two options here:
- 1. Having all the companies/organizations involved in the community. We would do that by using the standard version of our software, which shows all the companies found during the analysis. 
- 2. Showing just "Mozilla" and the rest of the world. This can be done if we keep maintaining a "fake" list of companies, where all the people who is not affiliated to Mozilla, becomes affiliated to "Community".

**Both options above take into account the affiliation data you provide. It does not affect the affiliation date created/imported for "Mozilla Corporation".**

The affiliation data affects not only the Git panel, but all the dashboard. If you go to the Github panels, they currently show affiliation as typed by the contributors on their github profile. The new version uses the main contributors database, so the information we choose will be even more visible.

@hmitsch I remember we talked about this months ago but we don't have a clear idea about what adds more value to your dashboard.

**Comment by hmitsch** [comment]
Let's use the following workaround:

* Email domains **mozilla.com** and **mozillafoundation.org**: Assign to **organization "Mozilla"**
* **Everything else**: Assign to organization **"Community"**

**Comment by hmitsch** [comment]
FYI, updated proposed organization name from "Mozilla" to "Mozilla Staff" to be consistent with https://github.com/mozilla/participation-metrics-identities/blob/master/RepsOrganizationTest1-organizations.yml

**Comment by hmitsch** [comment]
work in progress

**Comment by sanacl** [comment]
SH data 90% ready to be refreshed. The VM is not accessible right now. As soon as it ready again, we can start the refresh of the indexes.

**Comment by sanacl** [comment]
Git data is ready https://analytics.mozilla.community/app/kibana#/dashboard/Git

We have 30 commits assigned to Mozilla Corporation (less than 0.1%) but still don't understand why this happened ..

**Comment by hmitsch** [comment]
It's about 31 commits out of 3,494,887. Please don't worry about this anomaly. Let's close this issue. **Very well done!**
