### ISSUE TITLE
Kibana 5 upgrade

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#79]
Community Analytics will be upgraded to Kibana 5. It is currently estimated during March. As a consequence all panels will be updated to the lates Grimoire Lab panels (incl. enrichment libraries).

**Comment by sanacl** [comment]
We are ready to start pushing this.

We will need an upgrade of the current ES instance. AFAIK this is done creating a new instance, so we would need the new ES5 instance up & running at the same time for a couple of days (less than three) so we can switch it smoothly.

Steps:
- new ES 5.1 deployed (ParSys)
- raw indexes copied, new enriched indexes created (Bitergia)
- new panels/dashboards are uploaded (Bitergia)
- dashboard will point to new ES 5.x so old ES 2.x content is no longer needed (Bitergia)
- old ES 2.x is decommissioned (ParSys)

**Comment by hmitsch** [comment]
Hi @flamingspaz, can you help us with step 1?
* new ES 5.1 deployed (ParSys)

When could @sanacl get this from you?

-Henrik

**Comment by sanacl** [comment]
@flamingspaz can it be 5.1.1 ? If not please wait until I confirm

**Comment by flamingspaz** [comment]
We can go up to 5.5, would that be better?

**Comment by sanacl** [comment]
@flamingspaz No, we don't support versions above 5.1.x yet

**Comment by flamingspaz** [comment]
opened https://github.com/mozilla/partinfra-terraform/pull/169 which would give a new ES cluster on 5.1 (Amazon doesn't have 5.1.1 it looks like) with a new endpoint. Once it's merged I'll update this issue so y'all can move data to it.

**Comment by flamingspaz** [comment]
The new endpoint is https://search-bitergia-metrics-es-ewoai7ko3v7ta25jzsrsvkwnqq.us-west-1.es.amazonaws.com

Let me know when you've transferred the data over so I can remove the old one!

**Comment by sanacl** [comment]
@flamingspaz oupss, I didn't know this was ready. We're starting the copy today.

**Comment by sanacl** [comment]
@hmitsch Bitergia upgrade will be ready before Wednesday next week.

@flamingspaz I'll update you as soon as we can decommission the 2.x ES server

**Comment by sanacl** [comment]
I'm reviewing the status of this. Data should be up to date during the next 4 or 5 hours, so we are close to decommission the 2.x ES server.

**Comment by sanacl** [comment]
@hmitsch @flamingspaz 

We are done with this. I've been comparing the data and panels, please give us a couple of days before decommission the old ES 2.x server.

**Comment by sanacl** [comment]
@hmitsch @flamingspaz 

migration to Kibana 5 (at least in data sets) is ready, so elasticsearch 2.x server is no longer needed. Please confirm you've read this.

**Comment by flamingspaz** [comment]
Awesome, I will decommission the old 2.x server in the next week or so.

**Comment by sanacl** [comment]
Great. We are done here :)
