### ISSUE TITLE
Community Analytics Site: Explore authentication and access control options

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-metrics-org#8]
Not sure if this is even possible or what a solution could look like, but it would be ideal if we could have a way to easily authorize/remove people from being able to access this tool, rather than sending out the same user/pass combo to a variety of people.

Wondering if @comzeradd could think about this and provide some ideas/options.

@MichaelKohler has some thoughts.

**Comment by MichaelKohler** [comment]
My thoughts were around the current approach. It seems that currently .htaccess is used which would allow for new users with separate passwords. This would need to be done per user and by somebody who can change the .htaccess file and finally get it to the server. This is very cumbersome indeed. This would allow to have several users (and also to delete users if necessary) for the short-term.

Regarding Auth0 I can't say anything before looking at the tool itself.

**Comment by hmitsch** [comment]
Proposal: Open Community Analytics to all NDA'ed Mozillians.
Kindly requesting @comzeradd to comment on this idea.

**Comment by comzeradd** [comment]
That would be ideal. As Michael said the current .htaccess approach doesn't scale if we want to open this to more people or get auth bits from specific mozillians groups (eg. NDA).

I don't see an easy way of integrating Auth0 without altering kibana's authentication code.

@sanacl which are the current auth methods supported by kibana?

**Comment by hmitsch** [comment]
Dear Bitergia,
can you please check if it possible (and what it takes) to integrate Bitergia Community Analytics with auth0 (https://auth0.com/).
Best regards,
   Henrik

**Comment by jsmanrique** [comment]
We didn't know about Auth0 service. We need to check their service costs and how to integrate it with Kibana websites

**Comment by sanacl** [comment]
Hi @comzeradd, the current auth methods supported by Kibana are not free/open source. There is a component called shield which could do the trick, but it is propietary.
As soon as we have a clear idea about the integration with the Auth0 service we'll let you know.

**Comment by hmitsch** [comment]
Requirement clarification:
- Everybody has the same access
- Provide access to Community Analytics for all Staff + NDA'ed Mozillians (via auth0/LDAP integration)

**Comment by sanacl** [comment]
This could solve us the issue: https://auth0.com/docs/quickstart/backend/nginx

**Comment by hmitsch** [comment]
Blocked: Waiting for Mozilla's IAM infrastructure to be at the right point. 
@hmitsch will unblock this issue.

**Comment by hmitsch** [comment]
Done a long time ago. Access is controlled via the _Mozilla IAM Proxy_.
