### ISSUE TITLE
Incoherent "Last retrieval" date on Data Status panel for remo.

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#81]
According to the Remo panels, there is data available from Feb 18th, but having a look at the data status panel the date for "Last retrieval" is December 12th 2016.

**Comment by hmitsch** [comment]
<img width="582" alt="image" src="https://cloud.githubusercontent.com/assets/869692/23141979/cee0447c-f7b9-11e6-853c-7e9e7ec316e4.png">

**Comment by sanacl** [comment]
Software patch applied and data is refreshed. We are having some issues with this data source due to we are not using the latest release for it. We are upgrading it during the next 2 weeks (it will be transparent to you guys).

Could you please let me know where I can get the view of events you get in Reps? So I can review data is coherent with its data source.

**Comment by hmitsch** [comment]
Fixed.

**Comment by sanacl** [comment]
@hmitsch I'm having a look at the Data Status panel for remo and I see a incoherent message there. 
The Last Retrieval date is not today, but the data is updated. 

It took me a while to understand the reason so I'll try to explain it to you guys. We have two dates for remo data:
* D1 -> events starting date: represents when a event starts
* D2 -> last retrieval/update data: shows when data was updated on the dashboard
* K3 -> the time frame we use to query data with Kibana (the time filter on top right)

Let's use an example, today (March 9th) the last retrieval date for remo says data is two weeks old, but data is updated. Why?
* all the data collected for remo is not being displayed. The data displayed is the one filtered by K3
* our panel uses the K3 applied for the field D1. That means that unless we query data from future, we are not getting all the items collected
* the last retrieval date shows when events with starting date =< March 9th were updated.

This is why if you increase the time frame and query data from future, the remo data says it is updated up to today https://analytics.mozilla.community:443/goto/583b844f7cb06ca0c4d228724a1c1b59

This is only affecting Remo and I'm asking the developers to know whether there is a clean solution for it. Feel free to *reopen* the ticket if the workaround I provide is not enough.

**Comment by sanacl** [comment]
By tomorrow afternoon it will be ready

**Comment by sanacl** [comment]
Fixed at https://analytics.mozilla.community/app/kibana#/dashboard/Data-Status
