### ISSUE TITLE
ReMo "Initiative" in Community Analytics

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#9]
We would like to have the ReMo portal event field "Initiative" in Bitergia's community analytics. 

Context: The field content is the campaign that an event belongs to, e.g. MozActivate.
Requirement source: https://github.com/mozilla/activate.mozilla.community/issues/59

**Comment by hmitsch** [comment]
API analysis is currently ongoing on Bitergia side

**Comment by acs** [comment]
@hmitsch yes, we have this "campaign" field included in the raw item gathered from the ReMo API, so we can propagate it to the enriched items so it can be used in Kibana panels. Is it what you are looking for?

**Comment by acs** [comment]
@hmitsch in the v2 API this field is called Initiative directly. So we can just use it.

https://reps.mozilla.org/api/beta/events/132/

**Comment by hmitsch** [comment]
Expected delivery date: 12 OCT 2016

**Comment by sanacl** [comment]
Panel to be reviewed using the Remo v2. On top right you can see the initiatives, it that what you are looking for? 

https://mozilla.biterg.io/app/kibana#/dashboard/Reps2-Activities

**Comment by hmitsch** [comment]
Next step: @hmitsch and @nukeador (and @brianking) --> acceptance testing

**Comment by nukeador** [comment]
Initiatives seems to be working here :-)

**Comment by hmitsch** [comment]
Cool, closing issue. Thanks @nukeador!
