### ISSUE TITLE
Wrong Identities

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#93]
**Dashboard URL:** https://analytics.mozilla.community:443/goto/615f02527b6ad409a486e8cda0efece6

## Artifacts
This lists ```project:"aframevr"``` contributors from the ```Community``` organization.

<img width="685" alt="image" src="https://cloud.githubusercontent.com/assets/869692/24806599/a447e2a4-1bb5-11e7-8c18-a390f4901a2e.png">

## Issues
* Fernando Serrano is a Mozilla employee
* Diego Goberna is a contractor that it's working with us now

**Comment by MichaelKohler** [comment]
and "a-frobot" might be a bot that needs to be marked?

**Comment by sanacl** [comment]
* Fernando is using a private account. I have no data about him in the data we imported from Mozillians. BTW, we haven't updated that info in weeks. Is he a new employee?. I've just enrolled it manually
* Same with Diego. I've assigned manually.
* a-frobot was marked as bot

Data won't be updated until next refresh.

**Comment by hmitsch** [comment]
@sanacl thank you for the quick response.

Great that you marked ```a-frobot``` as a **bot**.

Please do not manually tag people like Fernando and Diego as employees. We need to find a proper way to do this.
* Fernando is vouched as employee on Mozillians.org. Why does this not seem to be populating into Community Analytics?
* Diego does not have a Mozillians.org account. This is something I would follow-up with.

Best regards,
   Henrik

**Comment by hmitsch** [comment]
Fixed.
