### ISSUE TITLE
Identity "Unknown" seems to be wrong

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#94]
**Dashboard URL:** https://analytics.mozilla.community:443/goto/74ef856984176e1edd3ddd7e026e13d8

# Artifacts
<img width="691" alt="image" src="https://cloud.githubusercontent.com/assets/869692/24806789/455f5bb8-1bb6-11e7-9ed1-7668e1494fea.png">

# Issues
Most of the people in the list should belong to the ```Mozilla Staff``` organization.

**Comment by sanacl** [comment]
Index is still being refreshed. It will be fixed when it is finished.

**Comment by sanacl** [comment]
Fixed.

**Comment by hmitsch** [comment]
Yay!! Thank you.
