### ISSUE TITLE
Update Reps organization with data provided

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#98]
Update Reps organization with [data provided](https://github.com/mozilla/participation-metrics-identities/blob/master/Community%20Analytics%20-%20Reps%20Organization%20-%20Test%201.csv)

**Comment by nukeador** [comment]
@couci Can you ping us as soon as you update the file with the latest changes?

**Comment by couci** [comment]
yes this will happen tomorrow morning, june 2nd CET

**Comment by nukeador** [comment]
@sanacl Let's wait for @couci OK before implemeting it on the dashboard.

**Comment by nukeador** [comment]
Note: Only include non-employees in the Reps organization.

**Comment by sanacl** [comment]
@nukeador @hmitsch I see Mozilla employees in the Reps CSV. 34 people with @mozilla.com and at least for some of them the time range overlaps with the period working for Mozilla.

Is that ok?

**Comment by nukeador** [comment]
We agreed to count them as staff.

**Comment by nukeador** [comment]
@couci did you update the list with the latest changes to the Reps population?

**Comment by nukeador** [comment]
@sanacl [The file](https://github.com/mozilla/participation-metrics-identities/blob/master/Community%20Analytics%20-%20Reps%20Organization%20-%20Test%201.csv) has been now updated. Note that we have divided the reps into "Mozilla Reps" and "Functional Reps" in order to track the two different profiles of people we have in the program, also we have update the end date of a lot of them.

**Comment by jgbarah** [comment]
> @sanacl The file has been now updated.

OK. We're using this file as we see it now.

**Comment by hmitsch** [comment]
The file with the updated Mozilla Reps identities change from https://github.com/mozilla/participation-metrics-identities/blob/master/Community%20Analytics%20-%20Reps%20Organization%20-%20Test%201.csv to https://github.com/mozilla/participation-metrics-identities/blob/master/Reps-2017-06-06.csv

@sanacl please make sure to use that new CSV file.

**Comment by jgbarah** [comment]
Thx, @hmitsch. This new file has both "Mozilla Reps" and "Funcional Reps". The scripts @lcanas was working with only considered "Mozilla Reps". Not sure we can consider the new tag, since that would mean changing the script that was already being validated.

Not sure what to do with the new tag, anyway: should we just consider it as "Mozilla Rep", with the above considerations about overlapping periods with "Mozilla Staff", or something else?

**Comment by nukeador** [comment]
"mozilla reps" and "functional reps" should have the same behavior about staff previously described.

**Comment by nukeador** [comment]
Let's confirm if this is done and close the issue if so please.

**Comment by sanacl** [comment]
The data was refresh during the last days using the former file, so the bucket "Functional Reps" is not available. 
Data about the file [Community Analytics - Reps Organization - Test 1.csv](https://github.com/mozilla/participation-metrics-identities/blob/master/Community%20Analytics%20-%20Reps%20Organization%20-%20Test%201.csv) is refresh for the Git and Bugzilla indexes.

**Comment by nukeador** [comment]
Ok @sanacl coudl we get an estimation on how long it would take to refresh data with the updated file?

Thanks!

**Comment by nukeador** [comment]
Also, to clarify, it was refreshed in the Bitergia server and not Mozilla's indexes right? Because I can't see them on our dashboard.

**Comment by nukeador** [comment]
Also I see that on Bitergia's indexes for github issues I can't get the updated list with Reps.

**Comment by sanacl** [comment]
Data is updated for the Git and Bugzilla indexes in the Bitergia server. The rest of the data sources should be ready there (Bitergia facilities) during the next 24 hours.

**Comment by sanacl** [comment]
Information already applied to all the indexes. I think we can close this ticket.

**Comment by nukeador** [comment]
Reopening:

* We don't have this in the production server with the latest csv provided

**Comment by nukeador** [comment]
@sanacl please, let's make sure this issue is updated. Thanks!

**Comment by jgbarah** [comment]
We need to clarify this, and likely we need the help of @sanacl here. AFAIK, in the test (Bitergia) ElasticSearch we have a CSV applied with includes, among other stuff, detailed dates for Mozilla Employees. We understood we should not apply that one to the Mozilla ES for now. Am I wrong? Are we referring to some other CSV?

**Comment by nukeador** [comment]
Employee data should NOT be in production. Only the Reps one. The latest file live here:

https://github.com/mozilla/participation-metrics-identities/blob/master/Reps-2017-06-06.csv

**Comment by jgbarah** [comment]
OK, thanks!

**Comment by nukeador** [comment]
Thanks, please let us know when this is done.

**Comment by nukeador** [comment]
Hi, can we get an update here. We would like to understand status and ETA.

Thanks!

**Comment by sanacl** [comment]
ETA for having this in analytics.mozilla.community is August 2nd EOB.

**Comment by sanacl** [comment]
@nukeador @hmitsch I see a new organization/group named "Functional Reps", please confirm you want this group also on our analytics dashboard. If you don't say anything, I will add it as it is part of the CSV file you gave us.

**Comment by nukeador** [comment]
Yes, we split the Reps group into Reps and Functional Reps, that's correct.

**Comment by sanacl** [comment]
Internal identities database updated. This is already done for Git and Github indexes.

Next ones will be mailing lists and bugzilla

**Comment by sanacl** [comment]
Done for:
* Git + Github
* Mailing lists.

To be done:
* Bugzilla
* Discourse
* Mediawiki
* Remo

Don't have information about organizations:
* Mozilla Club
* Twitter

**Comment by hmitsch** [comment]
Twitter can be removed because our license expired. Can you do that?

**Comment by sanacl** [comment]
All data sources will be fully refreshed during the migration to Kibiter 5. So it will be solved during the next 7 days.

**Comment by sanacl** [comment]
I confirm the data sources above have the affiliation data for Reps. Closing ticket.

**Comment by hmitsch** [comment]
@nukeador @MichaelKohler reps org affiliations are now available everywhere in Community Analytics dashboards (Discourse, Wiki, Mozilla Reps). :-)

**Comment by nukeador** [comment]
Thanks for all the work!
